### ISSUE TITLE
3.5.0如何自定义 BaseResultMap

### ISSUE THREAD

**Issue by weycan** [baomidou/generator#100]
#### 版本信息

​	生成器版本:3.5.0

​	数据库版本:mysq8.0.26

​	模板引擎版本:freemarker

#### 问题详情
3.4.0上的GlobalConfig 配置

    /**
     * 开启 BaseResultMap
     */
    private boolean baseResultMap = false;

    /**
     * 时间类型对应策略
     */
    private DateType dateType = DateType.TIME_PACK;

    /**
     * 开启 baseColumnList
     */
    private boolean baseColumnList = false;
3.5.0 如何实现的
![QQ截图20210827103233](https://user-images.githubusercontent.com/43022498/131062650-2402b5fa-5368-47ef-8b9b-1fb78b353315.jpg)

**Comment by jiangore** [comment]
new StrategyConfig.Builder().mapperBuilder().enableBaseResultMap()

**Comment by jiangore** [comment]
> 
> #### 版本信息
> 
> ​ 生成器版本:3.5.0
> 
> ​ 数据库版本:mysq8.0.26
> 
> ​ 模板引擎版本:freemarker
> #### 问题详情
> 
> 3.4.0上的GlobalConfig 配置
> 
> ```
> /**
>  * 开启 BaseResultMap
>  */
> private boolean baseResultMap = false;
> 
> /**
>  * 时间类型对应策略
>  */
> private DateType dateType = DateType.TIME_PACK;
> 
> /**
>  * 开启 baseColumnList
>  */
> private boolean baseColumnList = false;
> ```
> 
> 3.5.0 如何实现的
> ![QQ截图20210827103233](https://user-images.githubusercontent.com/43022498/131062650-2402b5fa-5368-47ef-8b9b-1fb78b353315.jpg)

new StrategyConfig.Builder().mapperBuilder().enableBaseResultMap()

**Comment by lanjerry** [comment]
@jiangore 他不是要这个吧，你这个是设置开启baseResultMap，他是要自定义
