### ISSUE TITLE
SqlServerQuery  tableFieldsSql  查询有点问题

### ISSUE THREAD

**Issue by AngelYHY** [baomidou/generator#101]
请将问题描述清楚,别耽误彼此打(xi)工(jiao)赚(nen)钱(mo)的时间.
如果能直接提供错误示例,请上传仓库或私发邮箱,对于私发邮箱的代码,承诺不泄露来源方信息(邮箱名,公司名等信息),阅后即焚.

#### 版本信息

​	生成器版本:3.4.0

​	数据库版本:Microsoft SQL Server 2019 (RTM-CU11) (KB5003249) - 15.0.4138.2 (X64) 

​	模板引擎版本:

#### 问题详情
select * from sys.extended_properties where major_id=327060301
order by minor_id

查询结果：
1	OBJECT_OR_COLUMN	327060301	1	MS_Description	机构名称
1	OBJECT_OR_COLUMN	327060301	2	MS_Description	医疗付款方式
7	INDEX	                        327060301    2	MS_Description	病案号
1	OBJECT_OR_COLUMN	327060301	3	MS_Description	健康卡号
#### 期望结果  tableFieldsSql 的 sql：   c.minor_id = b.column_id   后面再加上   and c.class=1 就可以了

**Comment by qmdx** [comment]
sql server 这个奇葩的数据库，每个版本都不一样，期望 pr 你的实现。

或者你可以注入 DataSourceConfig 的 IDbQuery dbQuery 属性使用自定义 sql
