### ISSUE TITLE
MyBatis Plus官网生成器的文档该更新啦

### ISSUE THREAD

**Issue by AneonCode** [baomidou/generator#104]
请将问题描述清楚,别耽误彼此打(xi)工(jiao)赚(nen)钱(mo)的时间.
如果能直接提供错误示例,请上传仓库或私发邮箱,对于私发邮箱的代码,承诺不泄露来源方信息(邮箱名,公司名等信息),阅后即焚.

#### 版本信息

​	生成器版本: 3.5.0

​	数据库版本: MySQL 8.0

​	模板引擎版本:

**Comment by lanjerry** [comment]
@AneonCode 测试用例->使用例子->文档 目前是按照这个顺序完善

**Comment by AneonCode** [comment]
OK，是否可以先在官网文档顶部加一个提示，最新版本的到Github查看readme。这样可能会好一些？

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2021年9月1日 10:00
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [baomidou/generator] MyBatis Plus官网生成器的文档该更新啦 (#104)


@AneonCode<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAneonCode&data=04%7C01%7C%7C931b00af3d3f4cdf892c08d96cec4608%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637660584309621211%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=7PYTlAa%2BKrutlg%2Fc2M6j1%2BlJhOX6UiNW0brChcAENmY%3D&reserved=0> 测试用例->使用例子->文档 目前是按照这个顺序完善

―

**Comment by lanjerry** [comment]
@AneonCode Github的readme现在还是有点问题的

**Comment by AneonCode** [comment]
好的

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2021年9月1日 10:05
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [baomidou/generator] MyBatis Plus官网生成器的文档该更新啦 (#104)


@AneonCode<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAneonCode&data=04%7C01%7C%7C157102a25ff34317912108d96cecf383%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637660587214597073%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=IGRWG%2FiUxm4qnf4Q0CJ%2FTyff5DOdlZ%2BQME9jdh2JuVU%3D&reserved=0> Github的readme现在还是有点问题的

―

**Comment by lanjerry** [comment]
@AneonCode 已经更新，最新版本为3.5.1
