### ISSUE TITLE
找不到 FastAutoGenerator  

### ISSUE THREAD

**Issue by pth-cocoon** [baomidou/generator#105]
请将问题描述清楚,别耽误彼此打(xi)工(jiao)赚(nen)钱(mo)的时间.
如果能直接提供错误示例,请上传仓库或私发邮箱,对于私发邮箱的代码,承诺不泄露来源方信息(邮箱名,公司名等信息),阅后即焚.

#### 版本信息

​	生成器版本: 3.5.0

​	数据库版本: mysql5.7

​	模板引擎版本:

#### 复现步骤
按照readme的代码
`FastAutoGenerator.create("url", "username", "password")
	.globalConfig(builder -> {
		builder.author("L.cm")
			.dateType(DateType.TIME_PACK)
			.fileOverride()
			.outputDir("目录");
	})
	.packageConfig(builder -> {
		builder.parent("net.xxxx.project")
			.moduleName("system");
	})
	.strategyConfig(builder -> {
		builder.addInclude("sys_xxx")
			.entityBuilder()
			.enableLombok()
			.superClass(BaseModel.class)
			.addSuperEntityColumns("id", "created_by", "created_at", "updated_by", "updated_at")
			.naming(NamingStrategy.underline_to_camel)
			.controllerBuilder()
			.superClass(BaseController.class)
			.enableRestStyle()
			.enableHyphenStyle()
			.mapperBuilder()
			.enableMapperAnnotation()
			.enableBaseResultMap()
			.enableBaseColumnList()
		;
	})
	.templateEngine(new FreemarkerTemplateEngine())
	.execute();
`
#### 错误结果
Cannot resolve symbol 'FastAutoGenerator'

**Comment by lanjerry** [comment]
@pth-cocoon 这个还未发版，近期在完善单元测试和使用例子

**Comment by Eveamu** [comment]
@lanjerry 大概什么时候能完成呢？

**Comment by lanjerry** [comment]
@Eveamu 中秋前，这个FastAutoGenerator的例子可能也会去掉

**Comment by lunfangyu** [comment]
> @Eveamu 中秋前，这个FastAutoGenerator的例子可能也会去掉

同样的问题找到了这里；
按你这回复的意思，是不是意味着下个版本你们要删除FastAutoGenerator这个类呢？

**Comment by lanjerry** [comment]
@lunfangyu 决定不删了

**Comment by MZHY08** [comment]
@lanjerry 快中秋了哦，等着用新版本呢。

**Comment by lunfangyu** [comment]
> @Eveamu 中秋前

中秋已经过了，什么时候发新版本呢

**Comment by lanjerry** [comment]
@qmdx 老板，赶紧发版了，在催了

**Comment by lanjerry** [comment]
@pth-cocoon @MZHY08 @lunfangyu 已经更新，最新版本为3.5.1
