### ISSUE TITLE
生成entity，enableActiveRecord(),生成pkVal（） 是protected，期望public

### ISSUE THREAD

**Issue by zyu13579** [baomidou/generator#109]
#### 版本信息 3.4.3.3

​	生成器版本: 3.5.0

​	数据库版本: 5.8

​	模板引擎版本: velocity-engine-core-2.3

#### 问题详情
生成entity，enableActiveRecord(),生成pkVal（） 是protected

#### 期望结果
生成entity，enableActiveRecord(),生成pkVal（） 是public

**Comment by lanjerry** [comment]
@zyu13579 已经改了呢，等发版 

https://github.com/baomidou/generator/commit/8416d14e00c7d047e69884a858df31a5b8ebc379
