### ISSUE TITLE
velocity生成kotlin Entity模板文件有误

### ISSUE THREAD

**Issue by mindleee** [baomidou/generator#113]
请将问题描述清楚,别耽误彼此打(xi)工(jiao)赚(nen)钱(mo)的时间.
如果能直接提供错误示例,请上传仓库或私发邮箱,对于私发邮箱的代码,承诺不泄露来源方信息(邮箱名,公司名等信息),阅后即焚.

#### 版本信息

​	生成器版本:3.5.0

​	数据库版本:mysql8

​	模板引擎版本:velocity 2.3

#### 问题详情
3.5.0 无法生成kotlin版本的Entity
#### 错误结果
提示模板有误
Caused by: java.lang.RuntimeException: org.apache.velocity.exception.ParseErrorException: Encountered "field" at /templates/entity.kt.vm[line 67, column 5]
#### 期望结果
目前暂时使用自定义模板，在截图位置增加${}解决
<img width="540" alt="WX20210915-102142@2x" src="https://user-images.githubusercontent.com/10495202/133359935-12122bcf-f2a3-4e3d-b35e-801fc7cac02f.png">

**Comment by lanjerry** [comment]
@mindleee 好的，感谢

**Comment by lanjerry** [comment]
https://github.com/lanjerry/generator/commit/bd886b7bb8698428066bc02966f48553e3f19cc3

**Comment by lanjerry** [comment]
@mindleee 已经修复，最新版本为3.5.1，https://github.com/lanjerry/generator/commit/bd886b7bb8698428066bc02966f48553e3f19cc3
