### ISSUE TITLE
需求列表

### ISSUE THREAD

**Issue by qmdx** [baomidou/generator#116]
1.优化策略配置的验证，新增表名、字段名的后缀过滤功能.
2.支持自定义模板文件.
3.支持自定义模板生成位置.
4.注入配置新增注入map，以便支持在模板渲染内容中使用自己的map.
5.service和serviceImpl的模板取消强关联绑定，支持只生成一个.
6.修复enableTableFieldAnnotation注解失效的BUG.
7.名称转换默认下划线转驼峰命名.
8.默认开启isSerialVersionUID的生成.
9.修复表名需不需要转换判断的bug.
10.修复和调整entity的Kotlin模板.
11.完善和修复测试用例.
12.完善文档.

**Comment by Max-Qiu** [comment]
加一个：`MySqlKeyWordsHandler` 更新至MySQL8了

**Comment by qmdx** [comment]
> 加一个：`MySqlKeyWordsHandler` 更新至MySQL8

请补充 pr

**Comment by watsonhaw5566** [comment]
> SqlKeyWordsHandler

这个有关联的pr吗？

**Comment by Max-Qiu** [comment]
> > SqlKeyWordsHandler
> 
> @Max-Qiu这个有关联的公关吗？

[update:MySqlKeyWordsHandler 添加MySQL8.0关键字](https://github.com/baomidou/generator/pull/121)
