### ISSUE TITLE
关闭生成实体时生成字段注解时，不生成表名注解，字段注解依然生成

### ISSUE THREAD

**Issue by fengwenyi** [baomidou/generator#119]
请将问题描述清楚,别耽误彼此打(xi)工(jiao)赚(nen)钱(mo)的时间.
如果能直接提供错误示例,请上传仓库或私发邮箱,对于私发邮箱的代码,承诺不泄露来源方信息(邮箱名,公司名等信息),阅后即焚.

#### 版本信息

​	生成器版本:3.5.0

​	数据库版本:8.0.20

​	模板引擎版本:

#### 问题详情

开启生成表字段注解，表名注解和字段注解都有生成。

> entityBuilder.enableTableFieldAnnotation();

这没有问题，问题是，没有上面代码，表名注解不生成，字段注解依然存在。

#### 期望结果

不开启字段注解，表名注解依然生成，字段注解不生成。

**Comment by lanjerry** [comment]
@fengwenyi 如果生成的字段属性和数据库字段不一致，都会生成字段注解的。比如你数据库test_name，名称转换默认下划线转驼峰，那就是test_name -> testName，字段注解是会生成的

**Comment by lanjerry** [comment]
@fengwenyi 已经修复‘下划线转驼峰策略，字段不做注解处理’ https://github.com/baomidou/generator/commit/6bc0756eafe2cef131f81ad4eb5f1a7efefc363c
