### ISSUE TITLE
mybatis-plus-generator 3.5.1版本使用Lombok模型生成的entity只有@Setter、@Getter导致需要自己修改成@Data或者写tostring等方法，旧版本比如3.4.1就没这个问题直接是@Data

### ISSUE THREAD

**Issue by ruoshuixuelabi** [baomidou/generator#120]
请将问题描述清楚,别耽误彼此打(xi)工(jiao)赚(nen)钱(mo)的时间.
如果能直接提供错误示例,请上传仓库或私发邮箱,对于私发邮箱的代码,承诺不泄露来源方信息(邮箱名,公司名等信息),阅后即焚.

#### 版本信息

​	生成器版本: mybatis-plus-generator 3.5.1

​	数据库版本: mysql 8

​	模板引擎版本: velocity

#### 问题详情
开启了Lombok模型，生成的entity只有@Setter、@Getter并且是没有tostring以及equals的，mybatis-plus-generator 3.4.1是使用的@Data。所以现在等于生成的实体类我都得一一添加tostring等方法，或者修改注解。目前通过自定义模板来解决了这个问题。这样设计的目的是什么呢？看了一下源码，3.4.1使用的还是@Data而最新版本只使用@Setter、@Getter呢
enableLombok

**Comment by qmdx** [comment]
特意去掉的，因为 @Data 编译性能太差了（默认不推荐了），建议有 ToString 需求的时候加下，或者调整下模板即可

**Comment by ruoshuixuelabi** [comment]
恩，自己修改模板这个不难，目前也是这么用的。我想了解一下@Data 编译性能太差了（默认不推荐了）这个是咋得到的呢？是经过大量测试还是什么呢？我看了一下官方，并没有提到关于这个注解性能以及不推荐的问题。

**Comment by ruoshuixuelabi** [comment]
> 特意去掉的，因为 `@Data` 编译性能太差了（默认不推荐了），建议有 `@ToString` 需求的时候加下，或者调整下模板即可

恩，自己修改模板这个不难，目前也是这么用的。我想了解一下@DaTa 编译性能太差了（默认不推荐了）这个是咋得到的呢？是经过大量测试还是什么呢？我看了一下官方，并没有提到关于这个注解性能以及不推荐的问题。
