### ISSUE TITLE
生成器查询到两个主键

### ISSUE THREAD

**Issue by amkile** [baomidou/generator#122]
#### 版本信息

​	生成器版本:3.5.1

​	数据库版本:postgre13

​	模板引擎版本:freemarker 2.3.30

#### 问题详情

_我通过debug看到，程序通过一个sql去查询表结构数据（如下）,这条sql直接执行会查出两个主键来id和phone（这个不是主键）,我数据库一共两张表，我将另一个表删除就能正常查到一个，我感觉这条sql有问题_

SELECT 
A.attname AS name,
format_type (A.atttypid,A.atttypmod) AS type,
col_description (A.attrelid,A.attnum) AS comment,
(CASE WHEN (SELECT COUNT (*)
FROM pg_constraint AS PC 
WHERE 
A.attnum = PC.conkey[1] 

**这里应该添加一个关联表的条件（我就不提交了，还怪麻烦的）
and C.oid = PC.conrelid**

AND PC.contype = 'p') > 0 THEN 'PRI' ELSE '' END) AS key 
FROM pg_class AS C,
pg_attribute AS A 
WHERE A.attrelid='"sys_user"'::regclass 
AND A.attrelid= C.oid 
AND A.attnum> 0 
AND NOT A.attisdropped 
ORDER  BY A.attnum

### 这是那个查询的表，然后执行上述sql，会查出两个PRI
-- ----------------------------
-- Table structure for sys_user
-- ----------------------------
DROP TABLE IF EXISTS "public"."sys_user";
CREATE TABLE "public"."sys_user" (
  "id" int8 NOT NULL,
  "username" varchar(255) COLLATE "pg_catalog"."default" NOT NULL,
  "password" varchar(255) COLLATE "pg_catalog"."default" NOT NULL,
  "phone" varchar(255) COLLATE "pg_catalog"."default",
  "has_del" bool NOT NULL DEFAULT false,
  "email" varchar(255) COLLATE "pg_catalog"."default",
  "gender" int2,
  "number" varchar(255) COLLATE "pg_catalog"."default",
  "avatar" text COLLATE "pg_catalog"."default",
  "register" varchar(16) COLLATE "pg_catalog"."default"
)
;
COMMENT ON COLUMN "public"."sys_user"."username" IS '用户名称';
COMMENT ON COLUMN "public"."sys_user"."password" IS '密码';
COMMENT ON COLUMN "public"."sys_user"."phone" IS '手机号';
COMMENT ON COLUMN "public"."sys_user"."has_del" IS '删除标志';
COMMENT ON COLUMN "public"."sys_user"."email" IS '使用的邮箱';
COMMENT ON COLUMN "public"."sys_user"."gender" IS '1男2女';
COMMENT ON COLUMN "public"."sys_user"."number" IS '编号';
COMMENT ON COLUMN "public"."sys_user"."avatar" IS '头像';
COMMENT ON COLUMN "public"."sys_user"."register" IS '注册类型（英文）';

-- ----------------------------
-- Primary Key structure for table sys_user
-- ----------------------------
ALTER TABLE "public"."sys_user" ADD CONSTRAINT "user_pkey" PRIMARY KEY ("id");

### 这个是另外一张表
-- ----------------------------
-- Table structure for sys_city
-- ----------------------------
DROP TABLE IF EXISTS "public"."sys_city";
CREATE TABLE "public"."sys_city" (
  "parent_code" varchar(255) COLLATE "pg_catalog"."default",
  "area_name" varchar(255) COLLATE "pg_catalog"."default",
  "level" int4,
  "area_code" varchar(255) COLLATE "pg_catalog"."default" NOT NULL
)
;

-- ----------------------------
-- Primary Key structure for table sys_city
-- ----------------------------
ALTER TABLE "public"."sys_city" ADD CONSTRAINT "city_pkey" PRIMARY KEY ("area_code");

**Comment by lanjerry** [comment]
@amkile 3.5.2版本，已经修改了PG数据库的查询SQL
