### ISSUE TITLE
无法创建文件，请检查配置信息！

### ISSUE THREAD

**Issue by zhangxinzhangxin01** [baomidou/generator#125]
请将问题描述清楚,别耽误彼此打(xi)工(jiao)赚(nen)钱(mo)的时间.
如果能直接提供错误示例,请上传仓库或私发邮箱,对于私发邮箱的代码,承诺不泄露来源方信息(邮箱名,公司名等信息),阅后即焚.

#### 版本信息

​	生成器版本: 3.5.1
​	数据库版本: Database server        = DB2/LINUXX8664 10.5.5
​	模板引擎版本:

#### 问题详情
db2生成表
com.ibm.db2.jcc.am.SqlException: DB2 SQL Error: SQLCODE=-443, SQLSTATE=38553, SQLERRMC=SYSIBM.SQLCOLUMNS;COLUMNS;SYSIBM:CLI:-727, DRIVER=4.29.24
#### 错误结果
无法创建文件，请检查配置信息！

**Comment by qmdx** [comment]
无 db2 环境，希望自行排查问题  pr
