### ISSUE TITLE
建议更新Latest release版本号

### ISSUE THREAD

**Issue by lunfangyu** [baomidou/generator#127]
v3.5.1版本已发布，但版本发布日志Latest release中仍为v3.5.0； 建议更新为最新版本，避免误导。
特别是官网链接过来的同学最容易误导，官网文档已显示为v3.5.1； 链接过来却看到v3.5.0； 会一脸蒙蔽

**Comment by lunfangyu** [comment]
> @lunfangyu 哪显示了3.5.0，截图或者给个链接

![截图_20211711111741](https://user-images.githubusercontent.com/41062458/136728531-a19c5a07-0fd6-4ee4-a74f-e482703486cd.png)

![截图_20211811111823](https://user-images.githubusercontent.com/41062458/136728556-bdc52b85-e214-4c59-850d-e37225aa415e.png)

**Comment by lanjerry** [comment]
@lunfangyu 好的，晚点改过来

**Comment by qmdx** [comment]
已处理
