### ISSUE TITLE
建议增加Entity自定义注解功能

### ISSUE THREAD

**Issue by lunfangyu** [baomidou/generator#129]
请将问题描述清楚,别耽误彼此打(xi)工(jiao)赚(nen)钱(mo)的时间.
如果能直接提供错误示例,请上传仓库或私发邮箱,对于私发邮箱的代码,承诺不泄露来源方信息(邮箱名,公司名等信息),阅后即焚.

#### 版本信息

​	生成器版本: V3.5.1

​	数据库版本: MySQL 5.7.34-log

​	模板引擎版本: freemarker 2.3.31

#### 问题详情
![实体字段注解](https://user-images.githubusercontent.com/41062458/137235901-437a57ca-a315-44b4-8fc8-c0592c0446c6.png)
如图所示，某些字段需要添加自定义注解，添加注解规则为：
1、类型为LocalDateTime的，添加日期格式和序列化、反序列化注解：@DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")、@JsonDeserialize(using = LocalDateTimeDeserializer.class)

2、当字段类型为Long且字段名后缀为"Id"时，添加@JsonSerialize(using = ToStringSerializer.class)注解；防止前端丢失精度。

#### 期望结果
希望在不使用自定义模板的前提下实现添加自定义注解；不知道是否有配置策略可实现?  或者有可扩展的接口可实现自定义导包的逻辑？ 如果没有，建议增加此功能，从实际项目来看，用到的比较多

**Comment by qmdx** [comment]
请使用自定义模板
