### ISSUE TITLE
关于生成文件是否覆盖的建议

### ISSUE THREAD

**Issue by lunfangyu** [baomidou/generator#132]
请将问题描述清楚,别耽误彼此打(xi)工(jiao)赚(nen)钱(mo)的时间.
如果能直接提供错误示例,请上传仓库或私发邮箱,对于私发邮箱的代码,承诺不泄露来源方信息(邮箱名,公司名等信息),阅后即焚.

#### 版本信息

​	生成器版本: V3.5.1

​        数据库版本: MySQL 5.7.34-log

#### 问题详情
当前版本在全局配置有.fileOverride()属性控制生成的文件是否覆盖旧文件。
但通常，像service、controller这些类只需生成一次即可，之后则需要再次生成修改。
而实体类entity则可能会生成多次；因为会常碰到加减字段的情况。
因此建议把.fileOverride()放到策略配置中

#### 期望结果
把.fileOverride()放到策略配置中，Entity、Controller、Mapper、service都有各自的fileOverride()策略属性

**Comment by yueqinghan** [comment]
正想提呢，这个跟我想的一样。顶一下！
我目前通过控制生成模块，临时解决了一下：
/**
 * 模板配置
 */
private static void templateConfig(TemplateConfig.Builder builder, boolean flag) {
    builder.disable()
            .entity("/templates/entity.java");
    if (flag) {
        builder.service("/templates/service.java")
                .serviceImpl("/templates/serviceImpl.java")
                .mapper("/templates/mapper.java")
                .mapperXml("/templates/mapper.xml");
    }
}
...
...
templateConfig(builder, scanner.apply("xxx").equals("y"))
希望下个版本能支持单独配置是否覆盖

**Comment by lanjerry** [comment]
@lunfangyu 3.5.2已实现
