### ISSUE TITLE
关于PackageConfig.Builder().mapperXml(String)方法有异议

### ISSUE THREAD

**Issue by sea158246forset** [baomidou/generator#133]
请将问题描述清楚,别耽误彼此打(xi)工(jiao)赚(nen)钱(mo)的时间.
如果能直接提供错误示例,请上传仓库或私发邮箱,对于私发邮箱的代码,承诺不泄露来源方信息(邮箱名,公司名等信息),阅后即焚.

#### 版本信息

​	生成器版本: 3.5.1 

​	数据库版本:

​	模板引擎版本:

#### 问题详情

文档错误:文档中写的是PackageConfig.Builder().mapperXml(String)，方法但是源码中只有PackageConfig.Builder().xml（string）方法不知道是后期改了方法名称，文档错误希望订正下

**Comment by lanjerry** [comment]
@sea158246forset 是文档有误，感谢提醒，已修正

**Comment by lanjerry** [comment]
@sea158246forset 3.5.2已修正
