### ISSUE TITLE
自定义模板的输出命名问题，看源码也没找到参数，好像是写死的拼接，无法自定义

### ISSUE THREAD

**Issue by ifanio** [baomidou/generator#134]
/**
     * 输出自定义模板文件
     *
     * @param customFile 自定义配置模板文件信息
     * @param tableInfo  表信息
     * @param objectMap  渲染数据
     * @since 3.5.1
     */
    protected void outputCustomFile(@NotNull Map<String, String> customFile, @NotNull TableInfo tableInfo, @NotNull Map<String, Object> objectMap) {
        String entityName = tableInfo.getEntityName();
        String otherPath = getPathInfo(OutputFile.other);
        customFile.forEach((key, value) -> {
            **_String fileName = String.format((otherPath + File.separator + entityName + File.separator + "%s"), key);_**
            outputFile(new File(fileName), objectMap, value);
        });
    }

**Comment by qmdx** [comment]
重写这个地方的逻辑自己处理，可以参考视频教程 【注入配置】

https://baomidou.com/guide/generator-new.html

**Comment by zhangzihang** [comment]
这就关闭了吗，我觉得这是个比较有用的问题，为图方便，之前我从来不生成IService，但是在3.5.1，我暂时找不到什么简单的方法使用自定义的模板，像3.4.1那样

**Comment by lanjerry** [comment]
@zhangzihang 不生成IService直接在模板配置禁用掉，如disable(TemplateType.SERVICE)，FileOutConfig这个有待讨论是否加回来
