### ISSUE TITLE
怎么在strategyConfig中addTablePrefix拿到packageConfig的moduleName？

### ISSUE THREAD

**Issue by hhf-123** [baomidou/generator#136]
请将问题描述清楚,别耽误彼此打(xi)工(jiao)赚(nen)钱(mo)的时间.
如果能直接提供错误示例,请上传仓库或私发邮箱,对于私发邮箱的代码,承诺不泄露来源方信息(邮箱名,公司名等信息),阅后即焚.

#### 版本信息

​	生成器版本:3.5.1

​	数据库版本:8.0.22

​	模板引擎版本:2.5.5 freemarker-stater

#### 问题详情
怎么在strategyConfig中addTablePrefix拿到packageConfig的moduleName？
#### 期望结果

**Comment by lanjerry** [comment]
@hhf-123 packageConfig的getModuleName()
