### ISSUE TITLE
.addInclude(scanner.apply(...))。不支持输入多个表

### ISSUE THREAD

**Issue by ccccpi** [baomidou/generator#137]
### 当前使用版本(必填,否则不予处理)
        <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-boot-starter</artifactId>
            <version>3.4.3.4</version>
        </dependency>

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
当我想要使用控制台输入多个表名的时候，会出错，单个表不会出错

### 重现步骤(如果有就写完整)

使用FastAutoGenerator创建，
```java
//FastAutoGenerator类
.strategyConfig((scanner, builder) -> builder
.addInclude(scanner.apply("请输入表名，多个表名字，请用,隔开："))
```

这里输入"tablename1","tablename2"不行，输入tablename1,tablename2也不行，最后都不会生成任何文件，查不到表名。

### 报错信息
16:40:12.129 [main] DEBUG com.baomidou.mybatisplus.generator.config.querys.MySqlQuery - 执行SQL:show table status WHERE 1=1  AND NAME IN ('sys_app,sys_config,sys_database_info,sys_dict,sys_dict_type,sys_file_info,sys_function,sys_log,sys_login_log,sys_role,sys_role_function,sys_subject,sys_user')
16:40:12.166 [main] DEBUG com.baomidou.mybatisplus.generator.config.querys.MySqlQuery - 返回记录数:0,耗时(ms):37
16:40:12.182 [main] DEBUG com.baomidou.mybatisplus.generator.AutoGenerator - ==========================文件生成完成！！！==========================
Disconnected from the target VM, address: '127.0.0.1:56069', transport: 'socket'

Process finished with exit code 0

### 进一步描述
直到看到上面的信息，才知道原来只能传入一个表名，当我按照逻辑——使用单引号并去掉第一个和最后一个的单引号——传入多个表名时，能够查询出来表，但无法生成文件

### 期望的结果
期望能够通过`.addInclude(scanner.apply("请输入表名"))`来达到能够传入多个表，并正确生成文件。
![Snipaste_2021-10-28_16-48-34](https://user-images.githubusercontent.com/27887703/139222654-d1a9c863-c49b-462f-9aac-7260d7cfbc15.png)
![Snipaste_2021-10-28_16-49-18](https://user-images.githubusercontent.com/27887703/139222666-202eb2bc-864b-4a89-ab6f-5081918b7565.png)
![Snipaste_2021-10-28_16-50-39](https://user-images.githubusercontent.com/27887703/139222670-766f7c4b-b908-4e9f-9529-8185d79f8a66.png)

**Comment by lanjerry** [comment]
@yueqinghan 3.5.2已支持
