### ISSUE TITLE
controllerMappingHyphenStyle

### ISSUE THREAD

**Issue by xlgo** [baomidou/generator#138]
#### 版本信息

​	生成器版本: 3.5.1

#### 问题详情
@RequestMapping("/sys/user-info")

controller.java.ftl   中 
<#if controllerMappingHyphenStyle??>${controllerMappingHyphen}<#else>${table.entityPath}</#if>

总是返回  controllerMappingHyphen （托峰值）

builder.controllerBuilder().enableHyphenStyle()   的值没问题

去掉 ?? 正常
#### 错误结果
@RequestMapping("/sys/user-info")
#### 期望结果
@RequestMapping("/sys/userInfo")

**Comment by lizhen789** [comment]
换 
<dependency>
            <groupId>org.apache.velocity</groupId>
            <artifactId>velocity-engine-core</artifactId>
            <version>2.3</version>
        </dependency>
就好了
