### ISSUE TITLE
mybatis-plus的代码生成器与达梦数据库8，生成代码时，实体类中无属性字段

### ISSUE THREAD

**Issue by luoxiyang** [baomidou/generator#14]
### 当前使用版本(必填,否则不予处理)
版本信息如下：
 <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-boot-starter</artifactId>
            <version>3.4.0</version>
        </dependency>

        <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>dynamic-datasource-spring-boot-starter</artifactId>
            <version>3.2.1</version>
        </dependency>

        <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-generator</artifactId>
            <version>3.4.0</version>
        </dependency>

        <dependency>
            <groupId>org.freemarker</groupId>
            <artifactId>freemarker</artifactId>
            <version>2.3.30</version>
        </dependency>

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
在达梦数据库建好表以后，通过代码生成器生成的代码中实体类无对应的属性字段。
表结构代码如下：
CREATE TABLE "CDECONOMY"."sys_user"
(
"id" BIGINT NOT NULL,
"account" VARCHAR(32) NOT NULL,
"pwd" VARCHAR(255) NOT NULL,
"salt_value" VARCHAR(32) NOT NULL,
"real_name" VARCHAR(64) NOT NULL,
"post" VARCHAR(64),
"mobile_phone" VARCHAR(20),
"tel_phone" VARCHAR(20),
"email" VARCHAR(64),
"user_photo" VARCHAR(255),
"is_init_pwd" TINYINT,
"lately_pwd_update_time" DATETIME(6),
"create_user_id" BIGINT,
"create_user_name" VARCHAR(255),
"create_time" DATETIME(6),
"update_user_id" BIGINT,
"update_user_name" VARCHAR(64),
"update_time" DATETIME(6),
"is_deleted" TINYINT DEFAULT 0,
"remark" VARCHAR(512),
CLUSTER PRIMARY KEY("id"),
UNIQUE("account")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "CDECONOMY"."sys_user" IS '用户表';
COMMENT ON COLUMN "CDECONOMY"."sys_user"."account" IS '账号';
COMMENT ON COLUMN "CDECONOMY"."sys_user"."create_time" IS '创建时间';
COMMENT ON COLUMN "CDECONOMY"."sys_user"."create_user_id" IS '创建人ID';
COMMENT ON COLUMN "CDECONOMY"."sys_user"."create_user_name" IS '创建人名称';
COMMENT ON COLUMN "CDECONOMY"."sys_user"."email" IS '邮件';
COMMENT ON COLUMN "CDECONOMY"."sys_user"."is_deleted" IS '删除标志';
COMMENT ON COLUMN "CDECONOMY"."sys_user"."is_init_pwd" IS '是否是初始化密码';
COMMENT ON COLUMN "CDECONOMY"."sys_user"."lately_pwd_update_time" IS '最近密码修改时间';
COMMENT ON COLUMN "CDECONOMY"."sys_user"."mobile_phone" IS '手机号码';
COMMENT ON COLUMN "CDECONOMY"."sys_user"."post" IS '职务';
COMMENT ON COLUMN "CDECONOMY"."sys_user"."pwd" IS '密码';
COMMENT ON COLUMN "CDECONOMY"."sys_user"."real_name" IS '真实姓名';
COMMENT ON COLUMN "CDECONOMY"."sys_user"."remark" IS '备注';
COMMENT ON COLUMN "CDECONOMY"."sys_user"."salt_value" IS '盐值';
COMMENT ON COLUMN "CDECONOMY"."sys_user"."tel_phone" IS '座机号码';
COMMENT ON COLUMN "CDECONOMY"."sys_user"."update_time" IS '更新时间';
COMMENT ON COLUMN "CDECONOMY"."sys_user"."update_user_id" IS '最后更新人ID';
COMMENT ON COLUMN "CDECONOMY"."sys_user"."update_user_name" IS '最后更新人名称';
COMMENT ON COLUMN "CDECONOMY"."sys_user"."user_photo" IS '头像';

代码生成器代码如下：
package com.cdeic.dmdbms.test;

import com.baomidou.mybatisplus.annotation.DbType;
import com.baomidou.mybatisplus.core.toolkit.StringPool;
import com.baomidou.mybatisplus.generator.AutoGenerator;
import com.baomidou.mybatisplus.generator.InjectionConfig;
import com.baomidou.mybatisplus.generator.config.*;
import com.baomidou.mybatisplus.generator.config.po.TableInfo;
import com.baomidou.mybatisplus.generator.config.rules.NamingStrategy;
import com.baomidou.mybatisplus.generator.engine.FreemarkerTemplateEngine;

import java.util.ArrayList;
import java.util.List;

/**
 * @author Administrator
 * @date 2020-9-10 13:46
 * @description 测试代码生成
 * @since 1.0
 */
public class CodeGenerator {

    public static void main(String[] args) {
        // 代码生成器
        AutoGenerator mpg = new AutoGenerator();

        // 全局配置
        GlobalConfig gc = new GlobalConfig();
        String projectPath = System.getProperty("user.dir");
        gc.setOutputDir(projectPath + "/src/main/java");
        gc.setAuthor("administrator");
        gc.setOpen(false);
        gc.setSwagger2(true);
        mpg.setGlobalConfig(gc);

        // 数据源配置
        DataSourceConfig dsc = new DataSourceConfig();
        dsc.setUrl("jdbc:dm://localhost:5236/CDECONOMY");
        dsc.setUsername("SYSDBA");
        dsc.setPassword("sysdba123456");
        dsc.setDriverName("dm.jdbc.driver.DmDriver");
        dsc.setDbType(DbType.DM);
        mpg.setDataSource(dsc);

        // 包配置
        PackageConfig pc = new PackageConfig();
        pc.setModuleName("user");
        pc.setParent("com.cdeic.dmdbms");
        mpg.setPackageInfo(pc);

        // 自定义配置
        InjectionConfig cfg = new InjectionConfig() {
            @Override
            public void initMap() {
                // to do nothing
            }
        };

        // 如果模板引擎是 freemarker
        String templatePath = "/templates/mapper.xml.ftl";

        // 自定义输出配置
        List<FileOutConfig> focList = new ArrayList<>();
        // 自定义配置会被优先输出
        focList.add(new FileOutConfig(templatePath) {
            @Override
            public String outputFile(TableInfo tableInfo) {
                // 自定义输出文件名 ， 如果你 Entity 设置了前后缀、此处注意 xml 的名称会跟着发生变化！！
                String[] arr = pc.getModuleName().split("\\.");
                String res = projectPath + "/src/main/resources/mapper/";
                for (int i = 0; i < arr.length; i++) {
                    res += arr[i];
                    if (i < arr.length - 1) {
                        res += "/";
                    }
                }
                res += "/" + tableInfo.getEntityName() + "Mapper" + StringPool.DOT_XML;
                return res;
            }
        });
        cfg.setFileOutConfigList(focList);
        mpg.setCfg(cfg);

        // 配置模板
        TemplateConfig templateConfig = new TemplateConfig();
        templateConfig.setXml(null);
        mpg.setTemplate(templateConfig);

        // 策略配置
        StrategyConfig strategy = new StrategyConfig();
        strategy.setNaming(NamingStrategy.underline_to_camel);
        strategy.setColumnNaming(NamingStrategy.underline_to_camel);
        strategy.setEntitySerialVersionUID(true);
        strategy.setEntityLombokModel(true);
        strategy.setRestControllerStyle(true);
        strategy.setInclude("sys_user");
        strategy.setControllerMappingHyphenStyle(true);
        strategy.setEntityTableFieldAnnotationEnable(true);
        mpg.setStrategy(strategy);
        mpg.setTemplateEngine(new FreemarkerTemplateEngine());
        mpg.execute();
    }

}

### 报错信息
无报错信息，生成的代码包含controller、entity、mapper、xml、service等，只有entity的实体字段为空

**Comment by nieqiurong** [comment]
排查下,执行下面SQL看有没有返回结果集，如果有的话，检查下是否自己自定义了实体模板。

```sql
SELECT T2.COLUMN_NAME,T1.COMMENTS,T2.DATA_TYPE ,CASE WHEN CONSTRAINT_TYPE='P' THEN 'PRI' END AS KEY FROM USER_COL_COMMENTS T1, USER_TAB_COLUMNS T2, (SELECT T4.TABLE_NAME, T4.COLUMN_NAME ,T5.CONSTRAINT_TYPE FROM USER_CONS_COLUMNS T4, USER_CONSTRAINTS T5 WHERE T4.CONSTRAINT_NAME = T5.CONSTRAINT_NAME AND T5.CONSTRAINT_TYPE = 'P')T3 WHERE T1.TABLE_NAME = T2.TABLE_NAME AND T1.COLUMN_NAME=T2.COLUMN_NAME AND T1.TABLE_NAME = T3.TABLE_NAME(+) AND T1.COLUMN_NAME=T3.COLUMN_NAME(+)   AND T1.TABLE_NAME = 'sys_user' ORDER BY T2.TABLE_NAME,T2.COLUMN_ID；


```
