### ISSUE TITLE
enableSkipView()

### ISSUE THREAD

**Issue by Mr-SunJun** [baomidou/generator#140]
版本信息
​ 生成器版本: 3.5.1

问题详情
// 策略配置
.strategyConfig((scanner, builder) -> builder.enableSkipView()

java.sql.SQLException: View 'biao.v_not_sitecode' references invalid table(s) or column(s) or function(s) or definer/invoker of view lack rights to use them

错误结果
.enableSkipView()使用这个函数并未跳过视图，和存储过程

期望结果
enableSkipView()跳过视图，以及存储过程

**Comment by lanjerry** [comment]
@Mr-SunJun 我用的mysql，发现这个属性没用到，开不开启都没有生成视图的
