### ISSUE TITLE
序列化suid只能生成1L吗

### ISSUE THREAD

**Issue by hhk93** [baomidou/generator#141]
请将问题描述清楚,别耽误彼此打(xi)工(jiao)赚(nen)钱(mo)的时间.
如果能直接提供错误示例,请上传仓库或私发邮箱,对于私发邮箱的代码,承诺不泄露来源方信息(邮箱名,公司名等信息),阅后即焚.

#### 版本信息

​	生成器版本:3.4.3.4

​	数据库版本:mysql8.0

​	模板引擎版本:velocity-engine-core-2.3

#### 问题详情
通过代码生成器生成实体类的时候序列化suid只能生成1L，不能生成动态的long吗？

**Comment by lanjerry** [comment]
@hhk93 暂不考虑
