### ISSUE TITLE
  Mybats-plus 生成代码时是否有接口获取数据库字段是否允许为null

### ISSUE THREAD

**Issue by 1hhh1** [baomidou/generator#142]
Mybats-plus 生成代码时是否有接口获取数据库字段是否允许为null。
  
![image](https://user-images.githubusercontent.com/66835834/140490150-cf80dda6-372f-44d7-a340-e3e58eb04e6e.png)

**Comment by qmdx** [comment]
可以暂时没有对我开放，你可以看下源码如何获取 DatabaseMetaDataWrapper 这个类

**Comment by 1hhh1** [comment]
谢谢 我来研究一下，我现在用sql语句查询出来结果 直接put到objectMap中 供在模板中使用


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "baomidou/generator"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月9日(星期二) 上午10:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [baomidou/generator]   Mybats-plus 生成代码时是否有接口获取数据库字段是否允许为null (Issue #142)





 
可以暂时没有对外开放，你可以看下源码如何获取 DatabaseMetaDataWrapper 这个类
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by MZHY08** [comment]
我在源码中找到了，就是图中的nullable，可以直接在模板中读取，找了好久终于找到了
<img width="639" alt="屏幕截图 2021-11-14 192858" src="https://user-images.githubusercontent.com/44521439/141679002-2573f834-258e-4804-9652-10c43d80c6d0.png">
