### ISSUE TITLE
默认模板使用自定义公共类会提示重写equals方法

### ISSUE THREAD

**Issue by fuguocheng** [baomidou/generator#143]
请将问题描述清楚,别耽误彼此打(xi)工(jiao)赚(nen)钱(mo)的时间.
如果能直接提供错误示例,请上传仓库或私发邮箱,对于私发邮箱的代码,承诺不泄露来源方信息(邮箱名,公司名等信息),阅后即焚.

#### 版本信息

​	生成器版本:3.5.1

​	数据库版本:Oracle 10g

​	模板引擎版本:velocity 2.3

#### 问题详情
默认模板生成实体类时，如果继承自定义的公共类，Sonarline会提示重写equals方法：
![152654_740ea82d_537121](https://user-images.githubusercontent.com/23301642/140888045-d32ff9b2-76fb-42a6-8c22-86089f01989d.png)
直接继承Model就不会有此提示。
解决方案可以自己修改模板文件，但版本升级后，还需要重新修改一次。是否可以将这种情况写进默认的模板文件中？

#### 复现步骤
1. 写一个公共类，继承Model
2. 实体类继承公共类

#### 错误结果
这不算错误，顶多算是个优化点

#### 期望结果
模板自动添加：@EqualsAndHashCode(callSuper = false)

**Comment by qmdx** [comment]
删除这条提示规则就行了，或者你调整下模块
