### ISSUE TITLE
使用disableSerialVersionUID，缺少依赖导入

### ISSUE THREAD

**Issue by MZHY08** [baomidou/generator#144]
#### 版本信息

​	生成器版本: 3.5.1

​	数据库版本: 8.0.25

​	模板引擎版本: velocity-engine-core:2.3

#### 问题详情
实体生成器使用disableSerialVersionUID，生成的实体内Serializable未导入依赖
```java
@Override
public Serializable pkVal() {
    return this.id;
}
```

#### 错误结果
缺少下方依赖
```java
import java.io.Serializable;
```

**Comment by lanjerry** [comment]
@MZHY08 disableSerialVersionUID是禁止生成序列化ID，要那个依赖干啥

**Comment by MZHY08** [comment]
> @MZHY08 disableSerialVersionUID是禁止生成序列化ID，要那个依赖干啥

问题详情中已经写了，即使用了disableSerialVersionUID，也会生成下面的pkVal方法，Serializable需要导包
