### ISSUE TITLE
生成实体的时候，表只有一个主键，但是会有两个TableId

### ISSUE THREAD

**Issue by reixuemin** [baomidou/generator#147]
请将问题描述清楚,别耽误彼此打(xi)工(jiao)赚(nen)钱(mo)的时间.
如果能直接提供错误示例,请上传仓库或私发邮箱,对于私发邮箱的代码,承诺不泄露来源方信息(邮箱名,公司名等信息),阅后即焚.

#### 版本信息

​	生成器版本:
3.5.1
​	数据库版本:
Postgresql 14
​	模板引擎版本:
velocity 2.3
#### 问题详情

生成实体的时候，会有两个TableId，我用p6spy打印了SQL日志，发现执行了这个SQL

Execute SQL：SELECT A.attname AS name,format_type (A.atttypid,A.atttypmod) AS type,col_description (A.attrelid,A.attnum) AS comment, (CASE WHEN (SELECT COUNT (*) FROM pg_constraint AS PC WHERE A.attnum = PC.conkey[1] AND PC.contype = 'p') > 0 THEN 'PRI' ELSE '' END) AS key FROM pg_class AS C,pg_attribute AS A WHERE A.attrelid='"table_name"'::regclass AND A.attrelid= C.oid AND A.attnum> 0 AND NOT A.attisdropped ORDER BY A.attnum;

这里面查找是否是主键用的
SELECT COUNT (*) FROM pg_constraint AS PC WHERE A.attnum = PC.conkey[1] AND PC.contype = 'p'
这样只是用attnum去查，确定不会查到其它表的主键吗？

#### 错误结果
![image](https://user-images.githubusercontent.com/14087655/142159463-a01747b6-7cab-43a5-b7e7-a9269458b72a.png)

**Comment by icodemo** [comment]
遇到同样的问题，会生成多个TableId，甚至都不是任意一个表的主键

**Comment by lanjerry** [comment]
@reixuemin @icodemo 3.5.2版本，已经修改了PG数据库的查询SQL
