### ISSUE TITLE
希望增加对于enum数据类型增加实体类生成的支持

### ISSUE THREAD

**Issue by MoonightsZ** [baomidou/generator#148]
#### 版本信息

​	生成器版本: 3.5.1

​	数据库版本: MariaDB 10.6

​	模板引擎版本:

#### 问题详情
目前生成器生成实体类时, 数据库类型为enum的字段, 在实体类中属性类型为String.

#### 期望结果
希望增加对于enum数据类型生成, 并把生成对应字段关联到这个enum

**Comment by qmdx** [comment]
请自行扩展
