### ISSUE TITLE
如何禁用模版引擎？？

### ISSUE THREAD

**Issue by 501956430** [baomidou/generator#150]
因为微服务用不上模版引擎，是否有开关可以控制？查看源码默认VelocityTemplateEngine 引擎。

`
public void execute(AbstractTemplateEngine templateEngine) {

        if (null == this.config) {
            this.config = new ConfigBuilder(this.packageInfo, this.dataSource, this.strategy, this.template, this.globalConfig, this.injection);
        }

        if (null == templateEngine) {
            templateEngine = new VelocityTemplateEngine();
        }

        ((AbstractTemplateEngine)templateEngine).setConfigBuilder(this.config);
        ((AbstractTemplateEngine)templateEngine).init(this.config).batchOutput().open();
        logger.debug("==========================文件生成完成！！！==========================");
    }
`

**Comment by qmdx** [comment]
生成代码放到 test 部分处理，修改依赖 scope
