### ISSUE TITLE
不能实现entity文件名下划线转驼峰，column不转

### ISSUE THREAD

**Issue by Spancymath** [baomidou/generator#152]
请将问题描述清楚,别耽误彼此打(xi)工(jiao)赚(nen)钱(mo)的时间.
如果能直接提供错误示例,请上传仓库或私发邮箱,对于私发邮箱的代码,承诺不泄露来源方信息(邮箱名,公司名等信息),阅后即焚.

#### 版本信息

​	生成器版本:3.5.1

​	数据库版本:8.0

​	模板引擎版本:
        
        <dependency>
            <groupId>org.apache.velocity</groupId>
            <artifactId>velocity-engine-core</artifactId>
            <version>2.0</version>
        </dependency>
        <dependency>
            <groupId>org.freemarker</groupId>
            <artifactId>freemarker</artifactId>
            <version>2.3.28</version>
            <scope>compile</scope>
        </dependency>

#### 问题详情
            .strategyConfig(builder ->
                    builder.entityBuilder()
                            .naming(NamingStrategy.underline_to_camel)
                            .columnNaming(NamingStrategy.no_change))
不能实现实体类名是驼峰，字段保持下划线

**Comment by lanjerry** [comment]
@Spancymath 已修复，下个版本更新
https://github.com/baomidou/generator/pull/146

**Comment by Spancymath** [comment]
好的
