### ISSUE TITLE
代码生成后，mapper.xml 中和 实体类的注解中，数据库中最后一个字段会有多余的字符出现

### ISSUE THREAD

**Issue by szyanimo** [baomidou/generator#154]
### 当前使用版本(必填,否则不予处理)

版本：3.5.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

代码生成后，mapper.xml 中和 实体类的注解中，数据库中最后一个字段会有多余的字符出现

### 重现步骤(如果有就写完整)

填写完配置信息后自动生成的代码

### 报错信息

![image](https://user-images.githubusercontent.com/48674541/144377332-65d81e47-f234-4678-8981-958b178f01b3.png)

**Comment by lanjerry** [comment]
@szyanimo 贴下配置和表结构，这边没复现到
![image](https://user-images.githubusercontent.com/32253589/146347680-f621a9d5-e6e1-42c6-ad5c-a8691453071b.png)
