### ISSUE TITLE
可以设置是否生成xml

### ISSUE THREAD

**Issue by Luooooooo** [baomidou/generator#155]
#### 版本信息

​	生成器版本:3.5.1

​	数据库版本:mysql8

​	模板引擎版本:VelocityTemplateEngine

#### 问题详情
无法设置不生成xml，builder.xml(null)会生成`null`文件夹
#### 期望结果
可以设置是否生成xml

**Comment by lanjerry** [comment]
@Luooooooo new TemplateConfig.Builder()
    .disable(TemplateType.XML)
