### ISSUE TITLE
可以做一个Oracle的例子么?怎么指定表所在的数据库

### ISSUE THREAD

**Issue by codeicu** [baomidou/generator#161]
oracle url是不带数schema的
又没看到哪里可以指定schema

**Comment by codeicu** [comment]
DataSourceConfig.Builder dscBuilder = new DataSourceConfig.Builder("jdbc:oracle:thin:@xxxx:1521:orcl", "xxxx", "xxxx");
        dscBuilder.schema("xxxx");
        FastAutoGenerator.create(dscBuilder)
                .globalConfig(builder -> {
                    builder.author("baomidou") // 设置作者
                            .enableSwagger() // 开启 swagger 模式
                            .fileOverride() // 覆盖已生成文件
                            .outputDir("D://"); // 指定输出目录
                })
                .packageConfig(builder -> {
                    builder.parent("com.baomidou.mybatisplus.samples.generator") // 设置父包名
                            .moduleName("system") // 设置父包模块名
                            .pathInfo(Collections.singletonMap(OutputFile.mapperXml, "D://")); // 设置mapperXml生成路径
                })
                .strategyConfig(builder -> {
                    builder
//                            .addInclude("xxxx") // 设置需要生成的表名
                            .addTablePrefix("t_", "c_") // 设置过滤表前缀
                    ;
                })
                .templateEngine(new FreemarkerTemplateEngine()) // 使用Freemarker引擎模板，默认的是Velocity引擎模板
                .execute();

    }

**Comment by lanjerry** [comment]
@codeicu 
https://github.com/baomidou/generator/blob/develop/mybatis-plus-
generator/src/test/java/com/baomidou/mybatisplus/generator/samples/OracleGeneratorTest.java
