### ISSUE TITLE
数据库与项目编码不同时生成的注释乱码

### ISSUE THREAD

**Issue by zhaofy2323** [baomidou/generator#163]
#### 版本信息

​	生成器版本:3.5.1

​	数据库版本:5.1.70

​	模板引擎版本:Velocity 2.0

#### 问题详情
由于数据库是很老的版本，并且使用了latin1，项目现在是utf8编码，导致了生成的entity字段注释乱码。。。
#### 错误结果
中文注释乱码
#### 期望结果
字段中的中文用了typeHandler转码了，但是字段的中文注释不知道是否支持typeHandler

**Comment by lanjerry** [comment]
@zhaofy2323 找不到这么版本的mysql，欢迎解决了PR

**Comment by zhaofy2323** [comment]
> 

应该跟版本没太大关系，主要是编码的问题，数据库 与 项目的编码不相同，注释就乱码了

**Comment by lanjerry** [comment]
@zhaofy2323 我把编码设置成latin1，生成的注释也没有乱码，能否提供下你的生成配置代码完整贴下和表结构

**Comment by zhaofy2323** [comment]
> @zhaofy2323 我把编码设置成latin1，生成的注释也没有乱码，能否提供下你的生成配置代码完整贴下和表结构

CREATE TABLE IF NOT EXISTS `acc_log` (
  `id` int(11) NOT NULL auto_increment,
  `adminid` int(11) NOT NULL default '0' COMMENT '管理id',
  `operator` varchar(50) NOT NULL default '0' COMMENT '操作',
  `ip` varchar(50) NOT NULL default '',
  `memberid` int(11) NOT NULL default '0',
  `datetime` datetime NOT NULL default '0000-00-00 00:00:00',
  `updsql` mediumtext NOT NULL,
  `accid` int(11) NOT NULL,
  PRIMARY KEY  (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1 ;

**Comment by zhaofy2323** [comment]
/**
     * 数据源配置
     */
    private static final DataSourceConfig.Builder DATA_SOURCE_CONFIG = new DataSourceConfig
            .Builder("jdbc:mysql://127.0.0.1:3306/test?characterEncoding=cp1252&useSSL=false&zeroDateTimeBehavior=convertToNull", "root", "123456");
            

    /**
     * 执行 run
     */
    public static void main(String[] args) throws SQLException {
//        before();
        FastAutoGenerator.create(DATA_SOURCE_CONFIG)
                // 全局配置
                .globalConfig((scanner, builder) -> builder
                        .author(scanner.apply("请输入作者名称？"))
                        .enableSwagger()
                        .outputDir("K:/idea_workspace/XXXX"+"/src/main/java")
                        .commentDate("yyyy-MM-dd")
                        .disableOpenDir()
                        )
                // 包配置
                .packageConfig((scanner, builder) -> builder
                        .parent(scanner.apply("请输入包名？"))
                )
                // 策略配置
                .strategyConfig((scanner, builder) -> builder
                        //表名
                        .addInclude(scanner.apply("请输入数据表名称？"))
                        .entityBuilder()
                            .enableLombok()
                            .enableTableFieldAnnotation()
                        .controllerBuilder()
                            .enableRestStyle()
                        .mapperBuilder()
                            .enableBaseResultMap()
                            .enableBaseColumnList()
                )
                /*
                    模板引擎配置，默认 Velocity 可选模板引擎 Beetl 或 Freemarker
                   .templateEngine(new BeetlTemplateEngine())
                   .templateEngine(new FreemarkerTemplateEngine())
                 */
                .execute();
    }

**Comment by lanjerry** [comment]
@zhaofy2323 
![image](https://user-images.githubusercontent.com/32253589/155113305-53f6aa68-02de-415c-a472-b7e64949380e.png)

**Comment by zhaofy2323** [comment]
@lanjerry 好的，可能是数据库版本的问题，我再研究研究，麻烦您了，谢谢
