### ISSUE TITLE
未指定moduleName时，生成的controller的requestmapping里会生成两个//

### ISSUE THREAD

**Issue by mostcool** [baomidou/generator#17]
### 当前使用版本(必填,否则不予处理)
3.4.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
代码生成器中，没有指定moduleName时，生成的controller的requestmapping里会生成两个//

**Comment by nieqiurong** [comment]
暂时package.setModuleName(null),以前pr改出来的问题.
https://github.com/baomidou/mybatis-plus/issues/2192

**Comment by nieqiurong** [comment]
https://github.com/baomidou/mybatis-plus/issues/2621

**Comment by mostcool** [comment]
@nieqiurong 全使用的是默认模板。应该是velocity吧。

**Comment by nieqiurong** [comment]
> @nieqiurong 我使用的是默认模板。应该是velocity吧。

上传个工程或者发送一份到我邮箱里看下.

**Comment by mostcool** [comment]
> > @nieqiurong 我使用的是默认模板。应该是velocity吧。
> 
> 上传个工程或者发送一份到我邮箱里看下.

@nieqiurong demo已经发送到你的邮箱。

**Comment by nieqiurong** [comment]
> > > @nieqiurong 我使用的是默认模板。应该是velocity吧。
> > 
> > 
> > 上传个工程或者发送一份到我邮箱里看下.
> 
> @nieqiurong demo已经发送到你的邮箱。
不再考虑velocity引擎1.x版本,请升级velocity-spring-boot-starter,或者单独引入velocity-spring-boot-starter即可.
```java
<!--        <dependency>-->
<!--            <groupId>com.alibaba.boot</groupId>-->
<!--            <artifactId>velocity-spring-boot-starter</artifactId>-->
<!--            <version>1.0.4.RELEASE</version>-->
<!--        </dependency>-->

        <dependency>
            <groupId>org.apache.velocity</groupId>
            <artifactId>velocity-engine-core</artifactId>
            <version>2.2</version>
        </dependency>
```

**Comment by nieqiurong** [comment]
#5
