### ISSUE TITLE
No suitable driver found for jdbc:mysql:

### ISSUE THREAD

**Issue by renhwfd** [baomidou/generator#171]
请将问题描述清楚,别耽误彼此打(xi)工(jiao)赚(nen)钱(mo)的时间.
如果能直接提供错误示例,请上传仓库或私发邮箱,对于私发邮箱的代码,承诺不泄露来源方信息(邮箱名,公司名等信息),阅后即焚.

#### 版本信息

​	生成器版本:3.5.1

​	数据库版本:5.7

​	模板引擎版本:

#### 问题详情
No suitable driver found for jdbc:mysql:
#### 复现步骤
快速生成代码的时候
#### 错误结果
No suitable driver found for jdbc:mysql:

**Comment by renhwfd** [comment]
![image](https://user-images.githubusercontent.com/42169820/150623666-a564ca2e-018f-473e-a00b-987186443244.png)

**Comment by lanjerry** [comment]
@renhwfd 老铁，我这边OK啊，你是不是没引驱动
