### ISSUE TITLE
新版本 MPBG 如何在不自定义转换器的情况下将 Mysql 的 Blob 和 Clob 列类型转换为 Java 中的 String 类型

### ISSUE THREAD

**Issue by calvinit** [baomidou/generator#174]
#### 版本信息

​	生成器版本: 3.5.1

​	数据库版本: Mysql 5.7.x

​	模板引擎版本: velocity 2.3

#### 问题详情

如何将数据库中 Blob 或 Clob 类型转换为 Java 中的 String 字符串类型呢？

#### 复现步骤

数据源配置如下：

FastAutoGenerator.create(new DataSourceConfig.Builder(url, username, password)
                        // 数据库查询
                        .dbQuery(new MySqlQuery())
                        // 数据库类型转换器
                        .typeConvert(new MySqlTypeConvert())
                        // 数据库关键字处理器
                        .keyWordsHandler(new MySqlKeyWordsHandler()))

#### 错误结果

生成的 Blob 类型对应了 java.sql.Blob 类型。

#### 期望结果

对应 String 类型。

**Comment by lanjerry** [comment]
@calvinit 目前只能自定义转换器处理
