### ISSUE TITLE
代码生成的StrategyConfig的setSuperMapperClass("")`是否可提供传Clazz<?>的重载方法？

### ISSUE THREAD

**Issue by shiwei-Ren** [baomidou/generator#18]
### 当前使用版本(必填,否则不予处理)

3.4.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

代码生成StrategyConfig配置Mapper父类，感觉可以提供一个传Clazz<?>的方法。像service、entity都提供了，唯独mapper没有。传全类名感觉没有传Clazz<?>兼容性好。

### 重现步骤(如果有就写完整)
```
StrategyConfig strategy = new StrategyConfig();
strategy
                /*
                    设置父类策略
                 */
                // 设置实体类的父类
                .setSuperEntityClass(BasicModel.class)
                //设置写入实体父类的字段
                .setSuperEntityColumns("create_time", "update_time", "create_by", "update_by")
                .setSuperMapperClass("marchsoft.base.BasicMapper")
                .setSuperServiceClass(IBasicService.class)
                .setSuperServiceImplClass(BasicServiceImpl.class);
```
### 建议
`setSuperMapperClass("marchsoft.base.BasicMapper")`是否可提供传Clazz<?>的重载方法？

**Comment by nieqiurong** [comment]
3.5.0快照版本.
```java
new StrategyConfig.Builder()
    .mapperBuilder().superClass(BasicMapper.class)
    .build();
```

**Comment by shiwei-Ren** [comment]
设置写入实体父类的字段是否提供了通过JavaBean属性的方式设置，可以解耦数据库.

`strategy.setSuperEntityColumns("create_time", "update_time", "create_by", "update_by")；`

**Comment by nieqiurong** [comment]
> 设置写入实体父类的字段是否提供了通过JavaBean属性的方式设置，可以解耦数据库.
> 
> `strategy.setSuperEntityColumns("create_time", "update_time", "create_by", "update_by")；`

setSuperEntityClass之后会自动识别父类公共字段.

**Comment by shiwei-Ren** [comment]
> > 设置写入实体父类的字段是否提供了通过JavaBean属性的方式设置，可以解耦数据库.
> > `strategy.setSuperEntityColumns("create_time", "update_time", "create_by", "update_by")；`
> 
> setSuperEntityClass之后会自动识别父类公共字段.

setSuperEntityClass之后会自动识别父类公共字段，好像并没有达到预期的效果。如果不加`strategy.setSuperEntityColumns("create_time", "update_time", "create_by", "update_by")；`。我生成的实体类还是会有如下的四个属性

```
@ApiModelProperty(value = "创建人id")
    private Long createBy;

    @ApiModelProperty(value = "更新人id")
    private Long updateBy;

    @ApiModelProperty(value = "创建时间")
    private LocalDateTime createTime;

    @ApiModelProperty(value = "更新时间")
    private LocalDateTime updateTime;

    @ApiModelProperty(value = "软删除（默认值为0，1为删除）")
    @TableField("is_deleted")
    private Boolean deleted;
```

**Comment by nieqiurong** [comment]
> > > 设置写入实体父类的字段是否提供了通过JavaBean属性的方式设置，可以解耦数据库.
> > > `strategy.setSuperEntityColumns("create_time", "update_time", "create_by", "update_by")；`
> > 
> > 
> > setSuperEntityClass之后会自动识别父类公共字段.
> 
> setSuperEntityClass之后会自动识别父类公共字段，好像并没有达到预期的效果。如果不加`strategy.setSuperEntityColumns("create_time", "update_time", "create_by", "update_by")；`。我生成的实体类还是会有如下的四个属性
> 
> ```
> @ApiModelProperty(value = "创建人id")
>     private Long createBy;
> 
>     @ApiModelProperty(value = "更新人id")
>     private Long updateBy;
> 
>     @ApiModelProperty(value = "创建时间")
>     private LocalDateTime createTime;
> 
>     @ApiModelProperty(value = "更新时间")
>     private LocalDateTime updateTime;
> 
>     @ApiModelProperty(value = "软删除（默认值为0，1为删除）")
>     @TableField("is_deleted")
>     private Boolean deleted;
> ```

补充上你字段策略与父类实体代码,并附加上现在使用的版本.

**Comment by shiwei-Ren** [comment]
#### mp使用版本
3.4.1

#### 代码
[仓库地址](https://github.com/shiwei-Ren/smpe-admin)

[代码生成类](https://github.com/shiwei-Ren/smpe-admin/blob/main/smpe-system/src/main/java/marchsoft/modules/generator/MybatisPlusGenerator.java)

[父类BasicModel.java](https://github.com/shiwei-Ren/smpe-admin/blob/main/smpe-common/src/main/java/marchsoft/base/BasicModel.java)

#### 父类
```
package marchsoft.base;

import com.baomidou.mybatisplus.annotation.FieldFill;
import com.baomidou.mybatisplus.annotation.TableField;
import com.baomidou.mybatisplus.core.conditions.AbstractWrapper;
import com.baomidou.mybatisplus.core.conditions.Wrapper;
import com.baomidou.mybatisplus.core.toolkit.support.SFunction;
import com.baomidou.mybatisplus.extension.activerecord.Model;
import com.baomidou.mybatisplus.extension.toolkit.SqlHelper;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Data;
import lombok.EqualsAndHashCode;
import marchsoft.enums.BaseMapperMethodEnum;
import org.apache.ibatis.session.SqlSession;

import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.Collection;

/**
 * description:公共实体类
 *
 * @author RenShiWei
 * Date: 2020/11/28 19:37
 **/
@EqualsAndHashCode(callSuper = true)
@Data
@ApiModel
public class BasicModel<T extends Model<?>> extends Model<T> implements Serializable {

    @ApiModelProperty(value = "创建者")
    @TableField(fill = FieldFill.INSERT)
    private String createBy;

    @ApiModelProperty(value = "更新者")
    @TableField(fill = FieldFill.INSERT_UPDATE)
    private String updateBy;

    @ApiModelProperty(value = "创建日期")
    @TableField(fill = FieldFill.INSERT)
    private LocalDateTime createTime;

    @ApiModelProperty(value = "更新时间")
    @TableField(fill = FieldFill.INSERT_UPDATE)
    private LocalDateTime updateTime;

    /**
     * description:重写父类的selectOne方法，添加"LIMIT 1"的限制，默认查第一条；
     * 防止selectList扫描全表，提高效率
     *
     * @param queryWrapper /
     * @return /
     * @author RenShiWei
     * Date: 2020/12/4 15:44
     */
    @Override
    public T selectOne(Wrapper<T> queryWrapper) {
        AbstractWrapper<T, SFunction<T, ?>, ?> abstractWrapper = (AbstractWrapper<T, SFunction<T, ?>, ?>) queryWrapper;
        abstractWrapper.last("LIMIT 1");
        return super.selectOne(abstractWrapper);
    }

    /**
     * description:批量新增，一条sql插入所有的sql语句<p>
     * 使用Collection<T>其中一个对象执行即可批量插入
     *
     * @param batchList 新增数据的集合对象
     * @return 是否执行成功
     * @author RenShiWei
     * Date: 2020/12/5 11:46
     */
    public boolean insertAllBatch(Collection<T> batchList) {
        SqlSession sqlSession = this.sqlSession();
        boolean var2;
        try {
            var2 = SqlHelper.retBool(sqlSession.insert(this.sqlStatement(BaseMapperMethodEnum.INSERT_ALL_BATCH.getMethod()), batchList));
        } finally {
            this.closeSqlSession(sqlSession);
        }
        return var2;
    }

}
```

**Comment by nieqiurong** [comment]
> setSuperEntityClass之后会自动识别父类公共字段，现在有问题，是会在下个版本，或者是在3.5.0解决吗？
> 
> 到时候是不是就可以自动识别，不用手动设置了。

现在使用3.5.0-SNAPSHOT即可.

**Comment by shiwei-Ren** [comment]
好的



---原始邮件---
发件人: "nieqiuqiu"<notifications@github.com&gt;
发送时间: 2020年12月18日(周五) 上午10:08
收件人: "baomidou/generator"<generator@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"shiwei-Ren"<1487660836@qq.com&gt;;
主题: Re: [baomidou/generator] 代码生成的StrategyConfig的setSuperMapperClass("")`是否可提供传Clazz<?&gt;的重载方法？ (#18)




  
setSuperEntityClass之后会自动识别父类公共字段，现在有问题，是会在下个版本，或者是在3.5.0解决吗？
 
到时候是不是就可以自动识别，不用手动设置了。
  
现在使用3.5.0-SNAPSHOT即可.
