### ISSUE TITLE
3.4.1的generator源码在哪里

### ISSUE THREAD

**Issue by bigger-xu** [baomidou/generator#180]
#### 版本信息

​	生成器版本: 3.4.1

​	数据库版本: 5.7

​	模板引擎版本: 2.3.31

#### 问题详情
3.4.1的generator源码在哪里看到，分支怎么找不到了？

**Comment by lanjerry** [comment]
@bigger-xu 3.4.1的分支已经删掉了，可以maven改3.4.1 Download Sources
