### ISSUE TITLE
新版本如何设置不生成Controller？

### ISSUE THREAD

**Issue by user20161119** [baomidou/generator#182]
请将问题描述清楚,别耽误彼此打(xi)工(jiao)赚(nen)钱(mo)的时间.
如果能直接提供错误示例,请上传仓库或私发邮箱,对于私发邮箱的代码,承诺不泄露来源方信息(邮箱名,公司名等信息),阅后即焚.

#### 版本信息

​	生成器版本:3.5.1

​	数据库版本:mysql 5.7.26-log

​	模板引擎版本:velocity默认版本

#### 问题详情
按照官方文档：https://baomidou.com/pages/779a6e/#%E5%BF%AB%E9%80%9F%E5%85%A5%E9%97%A8，配置，想实现不生成controller代码，根据文档https://baomidou.com/pages/981406/#%E6%A8%A1%E6%9D%BF%E9%85%8D%E7%BD%AE-templateconfig，尝试使用 `.templateConfig(tc->new TemplateConfig.Builder().disable(TemplateType.CONTROLLER)` 不生成controller层代码，但是并没有实现想要的结果。请问新版本支持不生成某层代码吗？

**Comment by lanjerry** [comment]
@user20161119 你想要的效果是什么？templateConfig的disable(xxxx)就是不生成某层的代码，如disable(TemplateType.CONTROLLER)就不会生成controller的代码

**Comment by user20161119** [comment]
> @user20161119 你想要的效果是什么？templateConfig的disable(xxxx)就是不生成某层的代码，如disable(TemplateType.CONTROLLER)就不会生成controller的代码

想要的效果：不生成controller层代码。
使用的配置如下：
```java
.strategyConfig(builder -> {
            builder.addInclude(getTables(dbName));// 设置需要生成的表名
            // .addTablePrefix("t_", "c_"); // 设置过滤表前缀
            builder.entityBuilder().enableLombok();
            builder.mapperBuilder().enableBaseColumnList().enableBaseResultMap();
            builder.serviceBuilder().formatServiceFileName("%sService").formatServiceImplFileName("%sServiceImpl");
        }).templateConfig(tc->new TemplateConfig.Builder().disable(TemplateType.CONTROLLER))
            .templateEngine(new VelocityTemplateEngine()) // 默认的是Velocity引擎模板
            .execute();
```
controller层代码还是生成了，看截图
![image](https://user-images.githubusercontent.com/123967/154183253-5687bc30-8d3b-4402-92f7-1a1334c4915a.png)

**Comment by lanjerry** [comment]
@user20161119 .templateConfig(tc->new TemplateConfig.Builder().disable(TemplateType.CONTROLLER))改成.templateConfig(tc->tc.disable(TemplateType.CONTROLLER))
