### ISSUE TITLE
使用自定义的metadata替换mysql的catalog信息，来生成数据

### ISSUE THREAD

**Issue by jintonghuoya** [baomidou/generator#183]
请将问题描述清楚,别耽误彼此打(xi)工(jiao)赚(nen)钱(mo)的时间.
如果能直接提供错误示例,请上传仓库或私发邮箱,对于私发邮箱的代码,承诺不泄露来源方信息(邮箱名,公司名等信息),阅后即焚.

#### 版本信息

​	生成器版本:3.5.1

​	数据库版本:8.0

​	模板引擎版本:freemarker

#### 问题详情
后续是否考虑支持自定义的metadata替换mysql的catalog信息
#### 复现步骤
后续是否考虑支持自定义的metadata替换mysql的catalog信息

**Comment by lanjerry** [comment]
@jintonghuoya 这个后续会看看，要看支持的数据库多不多

**Comment by jintonghuoya** [comment]
您好，邮件已收到。谢谢。---代新杰

**Comment by jintonghuoya** [comment]
> @jintonghuoya 这个后续会看看，要看支持的数据库多不多

嗯，我们公司最近要用到mysql这块，我看看先实现下
我简单看了下，ConfigBuilder#getTableInfoList方法里面也做了todo了，我应该只要写一个IDatabaseQuery的实现就行了

**Comment by jintonghuoya** [comment]
> @jintonghuoya 这个后续会看看，要看支持的数据库多不多

主要的工作量在数据转换

**Comment by jintonghuoya** [comment]
> @jintonghuoya hello，新版3.5.3 已发布，默认已采用元数据查询数据库信息的方式实现，防止不同版本所用的查询数据库信息的SQL语句不同的情况出现

强！！！
