### ISSUE TITLE
最新版FastAutoGenerator代码生成器无法支持db2 文件夹为空？？？

### ISSUE THREAD

**Issue by xfxf521** [baomidou/generator#184]
### 当前使用版本(必填,否则不予处理)

        <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-generator</artifactId>
            <version>3.5.1</version>
        </dependency>

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

       FastAutoGenerator.create(new DataSourceConfig.Builder("jdbc:db2://ip:50000/hbbip","xxxx","xxxxx")
                )
                .globalConfig(builder -> {
                    builder.author("test") // 设置作者
                            .outputDir("D://testdb2"); // 指定输出目录
                })
                .packageConfig(builder -> {
                    builder.parent("com.taikang") // 设置父包名
                            .pathInfo(Collections.singletonMap(OutputFile.mapperXml, "D://testdb2")); // 设置mapperXml生成路径
                })
                .strategyConfig(builder -> {
                    builder.enableCapitalMode()
                            .build();
                })
                .strategyConfig(builder -> {
                    builder.entityBuilder().enableLombok();
                })
                .strategyConfig(builder -> {
                    builder.controllerBuilder().controllerBuilder();
                })
                .execute();

**Comment by lanjerry** [comment]
@xfxf521 有没有报错信息啊大哥，看看查询表信息的sql是不是有问题

**Comment by xfxf521** [comment]
我不是使用mybatisplus 操作db2的crud有问题，这个是正常。是使用代码生成器无法逆向生成代码。文件夹为空。mysql是正常的。

**Comment by lanjerry** [comment]
@xfxf521 
SELECT * FROM SYSCAT.TABLES where tabschema='%s'

SELECT * FROM syscat.columns WHERE tabschema='%s' AND tabname='%s'

看看这两个语句执行下有没有结果

**Comment by xfxf521** [comment]
我现在有两个schema DB2INST1 和ROBOT和ipe_branch表。以下sql都是可以查询的出来结果的
select * from syscat.tables where (tabschema = 'DB2INST1' or tabschema='ROBOT')  with ur 

select * from syscat.columns where (tabschema = 'DB2INST1') and tabname = 'IPE_BRANCH' with ur

**Comment by lanjerry** [comment]
@xfxf521 你把生成器的打印出来的sql去执行下，看看有没有结果

**Comment by xfxf521** [comment]
15:27:56.197 [main] DEBUG com.baomidou.mybatisplus.generator.config.querys.DB2Query - 执行SQL:SELECT * FROM SYSCAT.TABLES where tabschema=current schema AND TABNAME IN ('T_XF_TEST_HBBIP')
15:27:56.228 [main] DEBUG com.baomidou.mybatisplus.generator.config.querys.DB2Query - 返回记录数:0,耗时(ms):29
15:27:56.228 [main] WARN com.baomidou.mybatisplus.generator.IDatabaseQuery$DefaultDatabaseQuery - 表[T_XF_TEST_HBBIP]在数据库中不存在！！！

但是这个sql在工具里面执行是存在的
SELECT * FROM SYSCAT.TABLES where tabschema=current schema AND TABNAME IN ('T_XF_TEST_HBBIP')

![image](https://user-images.githubusercontent.com/8255343/155673319-9d5e30a9-b74c-48bb-9c36-68a099d65ed8.png)

**Comment by lanjerry** [comment]
@xfxf521 估计是sql语句和你的db2版本不兼容，你可以重新下sql

**Comment by xfxf521** [comment]
刚刚测试了下另外一个版本，现在发现db2V97 和db2v10.5都无法生成

**Comment by lanjerry** [comment]
@xfxf521 你去查下对应版本的DB2的表和字段的SQL语句，重写下SQL就可以了，实现IDbQuery接口的tablesSql和tableFieldsSql
