### ISSUE TITLE
代码生成工具关于数据库字段not-null 是否能生成对应JSR的注解

### ISSUE THREAD

**Issue by jhx-zc** [baomidou/generator#191]
### 当前使用版本(必填,否则不予处理)
mybatis-plus generator:3.5.1 最新版

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
数据库对应字段声明时not null的，在`springboot`中希望能对entity使用validation 来减轻编码校验的工作。但是翻看doc没能找到相关的信息。（`enableTableFieldAnnotation`好像没有该功能）。

![image](https://user-images.githubusercontent.com/52167297/156493567-de5305fe-fc02-44e8-a736-53e115574860.png)

**Comment by techgoose** [comment]
我认为，根据阿里出品的Java开发手册的数据库的ORM章节，因为查询中禁止使用select *，所以对于DO类我们在定义上就必须全部支持Null，所以如果希望数据库约束了not null的就希望DO可以约束Null是不正确的。DO类为了满足简单，可复用的原则就应该是简单的get，set，全部默认null的实现。

如果你要进行业务约束，应该在DTO，Query类上下功夫。

当然，以上是我的浅见，如有错误，欢迎斧正。

**Comment by lanjerry** [comment]
@techgoose 说得对，但是他这个可能是自定义模板用到的需求，不一定是在entity的

**Comment by lanjerry** [comment]
@jhx-zc 参考这个，使用metaInfo的属性 https://github.com/baomidou/generator/issues/142
