### ISSUE TITLE
mybatis-plus-generator 3.5.3 问题收集

### ISSUE THREAD

**Issue by lanjerry** [baomidou/generator#192]
qmdx：
1. 数据验证，使用validation注解

lanjerry：
1. 支持父类公共字段使用属性名称
2. 尝试兼容旧版本自定义生成的FileOutConfig的功能

**Comment by weixiao5** [comment]
com.baomidou.mybatisplus.generator.engine AbstractTemplateEngine类中

自定义输出文件函数 输出目录filName 带了entityName，导致想自定义输出时候，目录不好配置，是否建议加一个配置或者一个链来单独配置化

` protected void outputCustomFile(@NotNull Map<String, String> customFile, @NotNull TableInfo tableInfo, @NotNull Map<String, Object> objectMap) {
        String entityName = tableInfo.getEntityName();
        String otherPath = this.getPathInfo(OutputFile.other);
        customFile.forEach((key, value) -> {
            String fileName = String.format(otherPath + File.separator + entityName + File.separator + "%s", key);
            this.outputFile(new File(fileName), objectMap, value, this.getConfigBuilder().getInjectionConfig().isFileOverride());
        });
    }`

**Comment by feiyan-gh** [comment]
Oracle数据库运行时如下错误：
java.sql.SQLException: ORA-00604: error occurred at recursive SQL level 1

**Comment by weixiao5** [comment]
您好，您的邮件我已经收到，我会尽快回复的。谢谢您的支持！

**Comment by SuperSuperZ** [comment]
**问题描述**：基于3.5.2版本生成器，数据库类型和JAVA类型不匹配。

**复现步骤**：MySQL中 " `ip` int(10) unsigned DEFAULT NULL,"的字段，生成实体类的Java类型是Integer。但数据库中无符号的int可以存储的值超过Integer.MAX_VALUE，导致查询出错。

**期望结果**:
对应关系可以参考mysql-connector-java这个包下com.mysql.cj.MysqlType这个枚举类。其他数据库类型，希望也能更新下对应关系。类型映射应该算是生成器的根本了，这个可不能出错呀。

**Comment by SuperSuperZ** [comment]
> **问题描述**：基于3.5.2版本生成器，数据库类型和JAVA类型不匹配。
> ....

查看之前的issues，发现有同学用"自定义类型转换器"解决类型转换错误的问题，确实可以暂时解决我现在遇到的情况了哈哈

**Comment by lihua-ya** [comment]
基于3.5.2版本生成器，oracle数据库
WARN com.baomidou.mybatisplus.generator.engine.VelocityTemplateEngine - Velocity 1.x is outdated, please upgrade to 2.x or later.
Exception in thread "main" java.lang.AbstractMethodError: oracle.jdbc.driver.T4CConnection.setSchema(Ljava/lang/String;)V

**Comment by lihua-ya** [comment]
基于3.5.1版本生成器，oracle数据库
WARN com.baomidou.mybatisplus.generator.engine.VelocityTemplateEngine - Velocity 1.x is outdated, please upgrade to 2.x or later.
Exception in thread "main" java.lang.AbstractMethodError: oracle.jdbc.driver.T4CConnection.setSchema(Ljava/lang/String;)V

**Comment by lihua-ya** [comment]
基于3.5.1版本生成器，oracle数据库11g
WARN com.baomidou.mybatisplus.generator.engine.VelocityTemplateEngine - Velocity 1.x is outdated, please upgrade to 2.x or later.
Exception in thread "main" java.lang.AbstractMethodError: oracle.jdbc.driver.T4CConnection.setSchema(Ljava/lang/String;)V

**Comment by lanjerry** [comment]
@lihua-ya 尝试升级3.5.2版本

**Comment by lihua-ya** [comment]
mybatisplus.generator 3.5.2版本，连接oracle数据库生成实体，oracle库表number类型字段生成java实体后，字段类型成BigDecimal，有什么解决办法

**Comment by lanjerry** [comment]
@lihua-ya 自定义类型转换器

**Comment by 1107115073** [comment]
mybatisplus.generator 3.5.2版本， 把 Sql server decimal 数据类型转成 java Double 类型，这是不合理，使用decimal就是为了精度，转换变成 Double，不就会出现精度丢失的问题。

**Comment by lanjerry** [comment]
@1107115073 你好，请通过自定义类型转换器实现

**Comment by weixiao5** [comment]
您好，您的邮件我已经收到，我会尽快回复的。谢谢您的支持！
