### ISSUE TITLE
解耦生成器生成代码和MP依赖

### ISSUE THREAD

**Issue by YangHgRi** [baomidou/generator#193]
#### 版本信息

​	生成器版本:3.5.2

​	数据库版本:8.0+

​	模板引擎版本:velocity 2.3

#### 问题详情
如何将生成器生成的代码和MB依赖解耦呢,有时候公司不让在项目里引入MB依赖,但还想用这个生成器提高生产效率.
#### 复现步骤
![image](https://user-images.githubusercontent.com/57426791/156786582-75e927ac-dc39-4d2c-a996-f4e97c411c05.png)
#### 错误结果
Mapper层和Service层类继承MP类.
#### 期望结果
不继承,方法写入Service和Mapper类中.

**Comment by lanjerry** [comment]
@YangHgRi 目前只能用自定义模板解决

**Comment by lm-lan** [comment]
单独弄个模块
