### ISSUE TITLE
代码生成器自定义entity service mapper路径失效

### ISSUE THREAD

**Issue by lipuAdmin** [baomidou/generator#196]
### 当前使用版本(必填,否则不予处理)
mybatis-plus 3.5.1
代码生成器  3.5.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

 1. 代码生成器自定义entity service mapper路径失效，我把他们均配置在dao包里，但是奇怪的是本该出现在resource下面的.xml文件出现在dao/mapper里，而，entity,service等均同级出现在父包mybatisPlus下。
 2. 如果只保留 .pathInfo(Collections.singletonMap(OutputFile.xml, property+"/src/main/resources/mapper"))的话，.xml可正常出现在/resources/mapper
 3. 我的配置如下

` builder.parent("com") // 设置父包名
                            .moduleName("mybatisPlus") // 设置父包模块名
                            .pathInfo(Collections.singletonMap(OutputFile.xml, property+"/src/main/resources/mapper"))
                            .pathInfo(Collections.singletonMap(OutputFile.service,property+"/src/main/java/com/mybatisPlus/dao/service"))
                            .pathInfo(Collections.singletonMap(OutputFile.entity,property+"/src/main/java/com/mybatisPlus/dao/entity"))
                            .pathInfo(Collections.singletonMap(OutputFile.serviceImpl,property+"/src/main/java/com/mybatisPlus/dao/service/impl"))
                            .pathInfo(Collections.singletonMap(OutputFile.mapper,property+"/src/main/java/com/mybatisPlus/dao/mapper"));`

**Comment by lanjerry** [comment]
@lipuAdmin 大哥，咱就说有没有一种可能，你的配置被覆盖了。。。。你写多个.pathInfo，后面的会覆盖前面的配置，也就是最后的OutputFile.mapper的路径配置才生效，参考H2CodeGeneratorTest的testCustomTemplatePath
https://github.com/baomidou/generator/blob/develop/mybatis-plus-generator/src/test/java/com/baomidou/mybatisplus/generator/samples/H2CodeGeneratorTest.java

**Comment by lipuAdmin** [comment]
@lanjerry  很奇怪，.pathInfo参数里的不同的的键（OutFile.xml  OutFile.service OutFile.entity）不是区别他们的吗？我理解的是这几个能够分别配置xml service entity包的路径。如果这样不行，那该如何分别配置 xml  service entity mapper包的路径呢？

**Comment by lanjerry** [comment]
@lipuAdmin 装在一个map里面啊，老铁
Map<OutputFile, String> pathInfo = new HashMap<>();
pathInfo.put(OutputFile.xml, "D://");
pathInfo.put(OutputFile.entity, "D://entity//");

**Comment by lipuAdmin** [comment]
好吧，懂了。这种链式编程不太熟悉
