### ISSUE TITLE
3.5.2版本fileOverride覆盖问题

### ISSUE THREAD

**Issue by Sancly** [baomidou/generator#199]
在全局配置器上设置覆盖文件，不生效，完全没有覆盖效果，是否改用其他api？但在3.5.1版本上可以实现覆盖

**Comment by lanjerry** [comment]
@Sancly 全局的已经弃用了，具体修改查看：
https://github.com/baomidou/generator/pull/157/commits/7a36255da27f6a66bf19f39e5f217d3ee5128fb8
