### ISSUE TITLE
fileOverride 无效

### ISSUE THREAD

**Issue by Alex-Zhuo** [baomidou/generator#200]
请将问题描述清楚,别耽误彼此打(xi)工(jiao)赚(nen)钱(mo)的时间.
如果能直接提供错误示例,请上传仓库或私发邮箱,对于私发邮箱的代码,承诺不泄露来源方信息(邮箱名,公司名等信息),阅后即焚.

#### 版本信息

​	生成器版本: 3.5.2

​	数据库版本: 8.0.26

​	模板引擎版本: FreemarkerTemplateEngine->2.3.28

#### 问题详情
fileOverride 在文件已存在时无效，无法覆盖已有文件

#### 期望结果
覆盖已有文件

**Comment by ykiZheng** [comment]
#132 有讲，现在只能单独设置。个人这样运行可行
```JAVA
// 策略配置
                .strategyConfig((scanner, builder) -> {
                    builder.addInclude(scanner.apply("请输入表名，多个表名用 , 隔开"))
                            .entityBuilder().fileOverride()// 覆盖已生成文件
                            .mapperBuilder().fileOverride();
//                            .addTablePrefix("s_", "c_");    // 设置过滤表前缀
                })
```
