### ISSUE TITLE
java: 找不到符号   符号:   变量 mapperXMl   位置: 类 com.baomidou.mybatisplus.generator.config.OutputFile

### ISSUE THREAD

**Issue by aq666888** [baomidou/generator#206]
请将问题描述清楚,别耽误彼此打(xi)工(jiao)赚(nen)钱(mo)的时间.
如果能直接提供错误示例,请上传仓库或私发邮箱,对于私发邮箱的代码,承诺不泄露来源方信息(邮箱名,公司名等信息),阅后即焚.

#### 版本信息

​	生成器版本:
          3.5.2
​	数据库版本:

​	模板引擎版本:

#### 问题详情
java: 找不到符号
  符号:   变量 mapperXMl
  位置: 类 com.baomidou.mybatisplus.generator.config.OutputFile
#### 错误结果
java: 找不到符号
  符号:   变量 mapperXMl
  位置: 类 com.baomidou.mybatisplus.generator.config.OutputFile

**Comment by yaokun1234** [comment]
遇到了同样的问题，降到3.5.1就没有这个问题了，或者将OutputFile.mapperXml 改成OutputFile.mapper.xml
<img width="352" alt="image" src="https://user-images.githubusercontent.com/84620029/163827614-370ea09c-7b55-4150-8209-21775943a57c.png">

**Comment by lanjerry** [comment]
@yaokun1234 hello，新版3.5.3 已修复此问题，有更好的建议，欢迎提issue

**Comment by aq666888** [comment]
ok,hurry up
