### ISSUE TITLE
建议放开config的继承

### ISSUE THREAD

**Issue by jacketzc** [baomidou/generator#218]
#### 版本信息

​生成器版本: 3.5.2

#### 问题详情
`GlobalConfig`、`PackageConfig`这些类的构造器都是私有的，这限制了某些业务场景的扩展性，比如我想新增加一种VO的生成方式，我不得不复制一份这些config才能做扩展处理

#### 期望结果

建议将config的构造器设定为public或者protected

**Comment by siminx** [comment]
多个自定义模板文件可能满足定制需求？
#205

**Comment by lanjerry** [comment]
@jacketzc hello，新版3.5.3 已发布，已重构了自定义文件生成的逻辑，详情请看

https://github.com/baomidou/generator/pull/240/commits/3af34e1b036e48c0f5074e88d3b1f2ea9889ceeb

例子：
https://github.com/baomidou/generator/blob/develop/mybatis-plus-generator/src/test/java/com/baomidou/mybatisplus/generator/samples/H2CodeGeneratorTest.java#L211
