### ISSUE TITLE
截断或重建表后 无法获取表注释

### ISSUE THREAD

**Issue by xiaoxiao6666** [baomidou/generator#219]
``请将问题描述清楚,别耽误彼此打(xi)工(jiao)赚(nen)钱(mo)的时间.
如果能直接提供错误示例,请上传仓库或私发邮箱,对于私发邮箱的代码,承诺不泄露来源方信息(邮箱名,公司名等信息),阅后即焚.

#### 版本信息

​	生成器版本:
 3.5.2
​	数据库版本:
 docker postgis 14-master
​	模板引擎版本:
velocity 2.2
#### 问题详情
截断表后表注释无法获取
#### 复现步骤
1.建表
`CREATE TABLE "public"."aaaaaa" (
  "id" int8 NOT NULL,
  CONSTRAINT "aaaaaa_pkey" PRIMARY KEY ("id")
)
;
COMMENT ON TABLE "public"."aaaaaa" IS '这是一个表的注解';
`
2.截断表
`TRUNCATE TABLE aaaaaa;`

3.执行生成
#### 错误结果
实体类无注释
#### 期望结果
1. 修改com.baomidou.mybatisplus.generator.config.querys.PostgreSqlQuery可解决问题
```
@Override
    public String tablesSql() {
        return "SELECT tb.table_name, d.description as comments\n" +
                "\n" +
                "FROM information_schema.tables tb\n" +
                "\n" +
                "JOIN pg_class c ON c.relname = tb.table_name\n" +
                "\n" +
                "LEFT JOIN pg_description d ON d.objoid = c.oid AND d.objsubid = '0'\n" +
                "\n" +
                "WHERE tb.table_schema = '%s'";
    }

    @Override
    public String tableName() {
        return "table_name";
    }
```

**Comment by lanjerry** [comment]
@xiaoxiao6666 这个是数据库版本不一致导致的，近期已在修复此类问题

**Comment by xiaoxiao6666** [comment]
好的谢谢
