### ISSUE TITLE
generator 自定义代码模板生成

### ISSUE THREAD

**Issue by fank243** [baomidou/generator#224]
### 当前使用版本(必填,否则不予处理)
mybatis-plus-generator:3.5.2

是否可以考虑像3.4.1一样提供自定义模拟板代码生成呢，新版只能支持内置的几个实现。

```java
fileList.add(new FileOutConfig("/ftl/api.java.ftl") {
      @Override
      public String outputFile(TableInfo tableInfo) {
          return outDir + "/api/" + "I" + tableInfo.getEntityName() + "Api" + StringPool.DOT_JAVA;
      }
});
```

**Comment by lanjerry** [comment]
@fank243 hello，新版3.5.3 已发布，已重构了自定义文件生成的逻辑，详情请看

https://github.com/baomidou/generator/pull/240/commits/3af34e1b036e48c0f5074e88d3b1f2ea9889ceeb

例子：
https://github.com/baomidou/generator/blob/develop/mybatis-plus-generator/src/test/java/com/baomidou/mybatisplus/generator/samples/H2CodeGeneratorTest.java#L211
