### ISSUE TITLE
3.5.2如何自定模板生成且指定路径

### ISSUE THREAD

**Issue by GravityMatrix** [baomidou/generator#228]
请将问题描述清楚,别耽误彼此打(xi)工(jiao)赚(nen)钱(mo)的时间.
如果能直接提供错误示例,请上传仓库或私发邮箱,对于私发邮箱的代码,承诺不泄露来源方信息(邮箱名,公司名等信息),阅后即焚.

#### 版本信息

​	生成器版本: 3.5.2

​	数据库版本:

​	模板引擎版本:

#### 问题详情
老版本是可以自定义模板生成得
改造新版本发现path OutputFile 限制了。
比如我想自定义生成BO, VO如何使用呢

**Comment by qmdx** [comment]
https://baomidou.com/pages/981406/#freemarker%E6%A8%A1%E7%89%88%E6%94%AF%E6%8C%81-dto-vo%E7%AD%89-%E9%85%8D%E7%BD%AE
