### ISSUE TITLE
当达DM梦数据库为大小写敏感时，表名使用驼峰风格会导致表字段获取为空，已定位源码

### ISSUE THREAD

**Issue by hn4930** [baomidou/generator#230]
#### 版本信息

​	生成器版本:  3.5.2以前的版本

​	数据库版本: 达梦8

​	模板引擎版本: 默认

#### 问题详情
当达梦数据库为大小写敏感时，表名使用驼峰风格会导致表字段获取为空
该问题在旧版中
[com/baomidou/mybatisplus/generator/config/builder/ConfigBuilder.java:572](/baomidou/mybatis-plus/blob/d0c8e2abe98f000eef89235976ff3f6cd66362ec/mybatis-plus-generator/src/main/java/com/baomidou/mybatisplus/generator/config/builder/ConfigBuilder.java#L590)
新版中
[com/baomidou/mybatisplus/generator/config/querys/DbQueryDecorator.java:110](/baomidou/generator/blame/386f9021000cdc54c7ae80f8f139b3676b10f752/mybatis-plus-generator/src/main/java/com/baomidou/mybatisplus/generator/config/querys/DbQueryDecorator.java#L110)

` } else if (DbType.DM == dbType) {
            tableName = tableName.toUpperCase();
            tableFieldsSql = String.format(tableFieldsSql, tableName);
        } `

均由该段代码导致，此处代码将驼峰表名转换为全大写导致字段查询为空

#### 复现步骤
达梦数据库设为大小写敏感，表名使用驼峰风格
#### 错误结果
表字段获取为空，实体类生成没有字段
#### 期望结果
entity正常生成字段

**Comment by lanjerry** [comment]
@hn4930 方便贴下你的表结构吗

**Comment by lanjerry** [comment]
@hn4930 老板，我刚试了一下，用了官网那个"大小写敏感"的版本的话，表和字段都是自动转为大写。你这个版本应该不是大小写敏感的版本但是后面自己重新设置了大小写敏感，你有2个解决方案：
1.后续生成器更新为3.5.3会默认元数据查询方式，不会有这个问题
2.实现IDbQuery接口，重写tablesSql和tableFieldsSql方法
