### ISSUE TITLE
3.5.2版本的建议

### ISSUE THREAD

**Issue by liuyiyo** [baomidou/generator#232]
请将问题描述清楚,别耽误彼此打(xi)工(jiao)赚(nen)钱(mo)的时间.
如果能直接提供错误示例,请上传仓库或私发邮箱,对于私发邮箱的代码,承诺不泄露来源方信息(邮箱名,公司名等信息),阅后即焚.

#### 版本信息

​	生成器版本:3.5.2

​	数据库版本:

​	模板引擎版本:

建议：
     最近用了一下新版的自动生成，提出几点建议（仅个人建议）：
1：java代码和mapper的生成地址能默认当前项目么，这个不应该是最基本的吗，为什么这个都不支持，不能理解。
2：Deprecated(覆盖fileOverride())的方法没有直接删除，为什么不生效（）？就写个3.5.3版本会删除此方法，代替的方法呢？？？？？
然后我误打误撞发现覆盖给放到Entity 策略配置里面了，但是文档又没更新。
3：@TableId没有对齐
![image](https://user-images.githubusercontent.com/52642305/173040263-7a58b3fb-3b55-4e79-8815-fad7b2077c61.png)

**Comment by lanjerry** [comment]
@liuyiyo hello
1.第一条建议在考虑，需要和团队沟通确定
2.fileOverride已新增了警告日志，并且后续发版会把替代方法更新到文档中
3.自测了Velocity，Beetl，Freemarker模板，均没有出现不对齐，这个应该跟你自己的IDEA设置有关

**Comment by lanjerry** [comment]
@liuyiyo hello，新版3.5.3 已发布，有更好的建议，欢迎提issue
