### ISSUE TITLE
3.5.2无法自定义生成文件。

### ISSUE THREAD

**Issue by Doubletreelin** [baomidou/generator#236]
#### 版本信息
​	生成器版本:3.5.2
​	数据库版本:mysql 5.7
​	模板引擎版本:org.freemarker 2.3.28

#### 问题详情
各位大佬，早上好。使用3.5.2的时候，无法像3.4版本一样，通过FileOutConfig的方式，自定义生成文件。因为平时搭建的项目中，一个项目的model有admin（后台管理系统），api（对外提供服务的后台）等。想通过generator的方式，一键生成admin的controller，service，mapper，api的controller，service，mapper。现在的生成貌似只能单服务生成吧。有点不方便。

尝试使用了customFile发现也不对，因为源码中com.baomidou.mybatisplus.generator.engine.AbstractTemplateEngine的方法把地址fileName写死了。就导致输出到controller的entityName下面的文件夹下了，这样和原系统的文件目录不一致了。还需要重新copy复制一下。

`    
protected void outputCustomFile(@NotNull Map<String, String> customFile, @NotNull TableInfo tableInfo, @NotNull Map<String, Object> objectMap) {
        String entityName = tableInfo.getEntityName();
        String otherPath = getPathInfo(OutputFile.other);
        customFile.forEach((key, value) -> {
            String fileName = String.format((otherPath + File.separator + entityName + File.separator + "%s"), key);
            outputFile(new File(fileName), objectMap, value, getConfigBuilder().getInjectionConfig().isFileOverride());
        });
    }
`

以上问题为使用过程中感觉不懂的地方，麻烦各位大佬解读以及指点！感谢了

**Comment by lanjerry** [comment]
@Doubletreelin 比如你的表是t_simple，那你通过自定义想生成的有什么文件

**Comment by lanjerry** [comment]
@Doubletreelin 抱歉，不太能明白你说的"手动重构路径"是什么意思，现在目前自定义生成文件的目录是 "other"+"表名"，然后需要自己拷贝到自己项目中去。你的期望效果是什么？能举例一下吗

**Comment by Doubletreelin** [comment]
@lanjerry 大佬，我可能解释不是很清楚，我举个例子吧。比如我想生成User表的Controller。现在的生成路径是“配置路径/Controller/User/UserController.java”，中间多了一个表名的文件夹。这样然后再拷贝到自己的项目中。之前用3.4.1的时候，我自己可以手动配置路径，这样，我就能定位到“项目路径/Controller/UserController.java”中，这样，就省略了一步复制过去了呢。简单一些。不知道现在的新版本能否实现呢？

**Comment by lanjerry** [comment]
@Doubletreelin 你说的都是自定义的？比如你上面说的Controller

**Comment by Doubletreelin** [comment]
@lanjerry 大佬是的呢。Controller我也写了些自定义的内容，在3.4.1中用generator的tableinfo，能取出表的相关信息，填充到freemarker的模板中，最后自动生成出来。

**Comment by Doubletreelin** [comment]
@lanjerry 大佬是的呢。Controller我也写了些自定义的内容，在3.4.1中用generator的tableinfo，能取出表的相关信息，填充到freemarker的模板中，最后自动生成出来。

**Comment by lanjerry** [comment]
@Doubletreelin 你这样试试，把模板文件替换成你的模板文件，比如替换controller文件，通过TemplateConfig的controller实现，new TemplateConfig.Builder().controller(“xxxx”).build()，然后输出目录GlobalConfig的outputDir改为你的项目路径。

**Comment by lanjerry** [comment]
@Doubletreelin 不过自定义文件，比如vo这些，就需要自己手动复制一下了，因为自定义文件是以表名为根据的，所以才会写死，后期看看能不能把之前的自定义文件那段逻辑兼容回去。

**Comment by Doubletreelin** [comment]
好的，那我试试。多谢大佬

**Comment by lanjerry** [comment]
@Doubletreelin hello，新版3.5.3 已发布，已重构了自定义文件生成的逻辑，详情请看

https://github.com/baomidou/generator/pull/240/commits/3af34e1b036e48c0f5074e88d3b1f2ea9889ceeb
