### ISSUE TITLE
遇到有外键的时候，外键字段的field.keyFlag=true，导致没法区分外键和主键

### ISSUE THREAD

**Issue by TTnTTT** [baomidou/generator#241]
遇到有外键的时候，外键字段的field.keyFlag=true，导致没法区分外键和主键，导致生成的实体类有两个@TableId注解

#### 版本信息

​	生成器版本:  mybatisplus3.5.1

​	数据库版本: postgresql12

​	模板引擎版本: freemarke2.3.28

#### 错误结果 
一个实体出现了两个@TableId

#### 期望结果
一个实体应该只有一个@TableId

**Comment by TTnTTT** [comment]
找到原因了，请修复一下
![image](https://user-images.githubusercontent.com/52871698/175928176-3c0403f7-0083-4465-99e6-2753456d03d8.png)

**Comment by TTnTTT** [comment]
com.baomidou.mybatisplus.generator.config.querys.PostgreSqlQuery 的tableFieldsSql()方法中的sql修改为：

```
"SELECT A.attname AS name,format_type (A.atttypid,A.atttypmod) AS type,col_description (A.attrelid,A.attnum) AS comment,\n" +
            "(CASE WHEN (SELECT COUNT (*) FROM pg_constraint AS PC WHERE A.attnum = PC.conkey[1] AND PC.contype = 'p' AND conrelid = A.attrelid) > 0 THEN 'PRI' ELSE '' END) AS key \n" +
            "FROM pg_class AS C,pg_attribute AS A WHERE A.attrelid='\"%s\"'::regclass AND A.attrelid= C.oid AND A.attnum> 0 AND NOT A.attisdropped ORDER  BY A.attnum"
```

**Comment by lanjerry** [comment]
@TTnTTT 后续改为元数据查询方式了，不采取这种走SQL的方式了，版本马上更新

https://github.com/baomidou/generator/blob/develop/mybatis-plus-generator/src/main/java/com/baomidou/mybatisplus/generator/query/DefaultQuery.java

**Comment by TTnTTT** [comment]
> 

好的，感谢

**Comment by lanjerry** [comment]
@TTnTTT hello，新版3.5.3 已发布

**Comment by TTnTTT** [comment]
> @TTnTTT hello，新版3.5.3 已发布

tag没有看到啊，主分支就是吗？

**Comment by TTnTTT** [comment]
> @TTnTTT hello，新版3.5.3 已发布

谢谢

**Comment by lanjerry** [comment]
@TTnTTT tag没更新，仓库已经有了

https://search.maven.org/search?q=a:mybatis-plus-generator

**Comment by TTnTTT** [comment]
> 

发现一个新bug，解决一下

**Comment by TTnTTT** [comment]
> @TTnTTT tag没更新，仓库已经有了
> 
> https://search.maven.org/search?q=a:mybatis-plus-generator

知道了，中央仓库没更新

**Comment by TTnTTT** [comment]
> @TTnTTT tag没更新，仓库已经有了
> 
> https://search.maven.org/search?q=a:mybatis-plus-generator

用了最新版我以前代码写的，生成出来代码好多问题，能修复一下3.5.1吗
