### ISSUE TITLE
injectionConfig  使用Custom(List<CustomFile> customFiles) 失效

### ISSUE THREAD

**Issue by dydhub** [baomidou/generator#244]
请将问题描述清楚,别耽误彼此打(xi)工(jiao)赚(nen)钱(mo)的时间.
如果能直接提供错误示例,请上传仓库或私发邮箱,对于私发邮箱的代码,承诺不泄露来源方信息(邮箱名,公司名等信息),阅后即焚.

#### 版本信息

​	生成器版本:     3.5.3

​	数据库版本: mysql:5.7

​	模板引擎版本: velocity:2.3

#### 问题详情
    injectionConfig 无法自定义包名
new CustomFile.Builder().fileName("VO.java").templatePath("/templates/vo.java.vm").packageName("model.vo").build()
设置packageName无效
#### 期望结果
希望可以自定义二级包名

**Comment by lanjerry** [comment]
@dydhub 先换成packageName("model/vo")，后续这个修复下
