### ISSUE TITLE
使用自定义类型转换的时候不生效

### ISSUE THREAD

**Issue by lsqmy** [baomidou/generator#248]
#### 版本信息

​	生成器版本:3.5.3

​	数据库版本:mysql 8

​	模板引擎版本:2.3.31

#### 问题详情
 使用自定义类型转换的时候不生效
#### 复现步骤
DataSourceConfig.Builder builder1 = new DataSourceConfig.Builder(url, username, password)
                .typeConvert((config, fieldType) -> {
这里写的内容不生效，有打印东西 没打出来 应该是没有执行这里的方法
})

#### 错误结果
自定义了数据库类型转换没有生效
#### 期望结果
期望生效

**Comment by wm26hua** [comment]
我也遇到了，你解决没

**Comment by ghostg00** [comment]
新版默认改了，用typeConvertHandler这个
