### ISSUE TITLE
3.5.1版本怎么只覆盖entity?

### ISSUE THREAD

**Issue by shotacon** [baomidou/generator#250]
只有一个fileOverride  但是不配置这个就完全不覆盖了

**Comment by qmdx** [comment]
暂不支持部分覆盖，你可以自行扩展重写部分逻辑

**Comment by lanjerry** [comment]
@shotacon 升级到3.5.3，可以进行单个覆盖了

**Comment by shotacon** [comment]
> @shotacon 升级到3.5.3，可以进行单个覆盖了

3q 已经升级上去了. 我研究一下
