### ISSUE TITLE
模板引擎上下文信息有没有预留主键信息？

### ISSUE THREAD

**Issue by zzpandaman** [baomidou/generator#252]
请将问题描述清楚,别耽误彼此打(xi)工(jiao)赚(nen)钱(mo)的时间.
如果能直接提供错误示例,请上传仓库或私发邮箱,对于私发邮箱的代码,承诺不泄露来源方信息(邮箱名,公司名等信息),阅后即焚.

#### 版本信息

​	生成器版本: 3.5.2

​	数据库版本: mysql  Ver 8.0.29 for Win64 on x86_64 

​	模板引擎版本: org.apache.velocity:velocity-engine-core:2.3

#### 问题详情
       看代码上下文信息是objectMap传进去的，请问有没有预留主键名字、主键类型字段

**Comment by zzpandaman** [comment]
我通过注入配置InjectionConfig提供的 beforeOutputFile((tableInfo, objectMap) -> {})接口遍历tableInfo的List<TableField> fields字段拿到了想要的结果

**Comment by qmdx** [comment]
up
