### ISSUE TITLE
驼峰转换设置后生成的实体类属性缺少TableField注解

### ISSUE THREAD

**Issue by zzb980881** [baomidou/generator#253]
#### 版本信息

​	生成器版本:
        3.5.3
​	数据库版本:
        mysql5
​	模板引擎版本:
        Freemarker
#### 问题详情
数据库字段命名本身是驼峰，设置驼峰转换后，生成的实体类属性缺少TableField注解，3.4.1版本是正常的。
见下图：
![图片](https://user-images.githubusercontent.com/1118228/181925328-bb9f5561-e0cd-45df-aa47-ac6aa5109e0d.png)
而3.4.1版本是这样的，下图
![图片](https://user-images.githubusercontent.com/1118228/181925362-179cdd1b-fdca-4d87-a91b-512895c4b154.png)
因全局配置是驼峰转换的，这样导致匹配数据库字段有误。

以下是调试信息，3.5.3版本如下图：
![图片](https://user-images.githubusercontent.com/1118228/182009359-345005b0-324f-456a-a0a2-3de0a17b0a88.png)

3.4.1版本如下图：
![图片](https://user-images.githubusercontent.com/1118228/182009416-5ab1f034-d076-4a00-86f8-1b4456e1778c.png)

**Comment by qmdx** [comment]
数据库本身就是驼峰写法，生成代码的时候不需要处理， MP 实体字段映射设置为驼峰命名即可

TableField 注解不是必须的
