### ISSUE TITLE
sql打印分析没有在 cmd 显示，代码生成器数据类型生成错误

### ISSUE THREAD

**Issue by zeng-you** [baomidou/generator#257]
#### 版本信息
​	spring-boot: 2.7.2
​	数据库: mysql8.0.29
​	java sdk: 17.0.3.1
​	p6spy: 3.9.1
​	mybatis-plus-generator: 3.5.3

#### 问题详情

共有两个问题：

第一个问题：sql调试没有在 cmd 打印 sql
提示：
Unable to make field private final java.lang.Class java.lang.invoke.SerializedLambda.capturingClass accessible: module java.base does not "opens java.lang.invoke" to unnamed module @30c15d8b

第﻿﻿二个问题：代码生成器数据类型生成错误
double 生成了 Object
tinyint 生成了 byte

**Comment by ghostg00** [comment]
同第二个问题
