### ISSUE TITLE
无法指定生成的主键的ID类型

### ISSUE THREAD

**Issue by jiang4yu** [baomidou/generator#26]
如果能直接提供错误示例,请上传仓库或私发邮箱.

对于私发邮箱的代码,承诺不泄露来源方信息(邮箱名,公司名等信息),阅后即焚.
![image](https://user-images.githubusercontent.com/50733847/102565514-91702b00-4118-11eb-97a6-df3b945e2645.png)
![image](https://user-images.githubusercontent.com/50733847/102565550-a6e55500-4118-11eb-9527-e12106338a6b.png)

#### 生成器版本与模板引擎版本
3.4.0

#### 错误信息
1. 最新版本3.4.1仍然存在；
2. 错误现象，在指定主键的ID类型后，仍无法正确使用指定的类型进行实体的生成

**Comment by lanjerry** [comment]
@jiang4yu 主键是不是设置成自增长了？

**Comment by jiang4yu** [comment]
> @jiang4yu 主键是不是设置成自增长了？

多谢提醒，与DBA确认了，数据库主键设置为自增了
