### ISSUE TITLE
请问在 CustomFile 上怎么配置可以生成固定名称的类，比如按 moduleName 生成 SpringBoot 启动类

### ISSUE THREAD

**Issue by liningsong** [baomidou/generator#264]
请将问题描述清楚,别耽误彼此打(xi)工(jiao)赚(nen)钱(mo)的时间.
如果能直接提供错误示例,请上传仓库或私发邮箱,对于私发邮箱的代码,承诺不泄露来源方信息(邮箱名,公司名等信息),阅后即焚.

#### 版本信息

​	生成器版本:3.5.3

​	数据库版本:8.0.29

​	模板引擎版本:

#### 期望结果
可以完整生成 SpringBoot 项目，包括 application.yml、pom.xml 和 Application.java 等这些和表没关系的文件

**Comment by lanjerry** [comment]
@liningsong 不支持，目前都是基于表来生成的
