### ISSUE TITLE
生成器换行符问题

### ISSUE THREAD

**Issue by guyi23** [baomidou/generator#267]
### 当前使用版本(必填,否则不予处理)
3.5.2 和 3.5.3都这样

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
使用generator生成的文件, 换行符不统一, mapper和service是LF, controller和entity为CRLF
希望提供配置项, 指定换行符
![企业微信截图_16633179737273](https://user-images.githubusercontent.com/50298854/190597166-5913beef-07fc-433b-b29f-829950df05e5.png)

### 重现步骤(如果有就写完整)
打开源码里的模板文件, 查看换行符就知道了, 见截图

**Comment by lanjerry** [comment]
@guyi23 这个跟你自己的IDEA有关，我的都是CRLF

**Comment by guyi233** [comment]
@lanjerry 我觉得不是, 看图
![1 jpg](https://user-images.githubusercontent.com/114651290/192978316-9bb90aec-8fef-4010-9975-d01f5065ea62.png)
![2 jpg](https://user-images.githubusercontent.com/114651290/192978346-8eb64aa1-01f5-4035-a3c7-34f1db5923aa.png)

**Comment by lanjerry** [comment]
![image](https://user-images.githubusercontent.com/32253589/193235209-d1bd3013-facf-4374-adf1-54449acb27a8.png)
@guyi233 那你可以改了PR上来，我这边是显示CRLF

**Comment by guyi233** [comment]
@lanjerry 应该和你git的设置有关, 你是不是打开了autocrlf? 我是从maven库上下的jar包, 直接解压, 发现不一致, 并不是看的源码;
不搞这个了, 问题不大, 我修改了jar包放本地用就OK了

**Comment by helloworld-will** [comment]
3.5.3 的mapper.java 也都是CRLF

**Comment by guyi233** [comment]
issue可以关了, 我看了源码没问题(都是LF, 说是CRLF的去查查git的AutoCrlf, 别被git骗了), 但maven仓库里的jar包确实不对, 可能时打包时有问题
