### ISSUE TITLE
V3.5.3 DateType.ONLY_DATE不生效

### ISSUE THREAD

**Issue by liukai237** [baomidou/generator#269]
请将问题描述清楚,别耽误彼此打(xi)工(jiao)赚(nen)钱(mo)的时间.
如果能直接提供错误示例,请上传仓库或私发邮箱,对于私发邮箱的代码,承诺不泄露来源方信息(邮箱名,公司名等信息),阅后即焚.

#### 版本信息

​	生成器版本: 3.5.3

​	数据库版本: MySQL 5.7

​	模板引擎版本: Velocity 2.3

#### 问题详情
3.5.2正常，datetime类型字段能正确映射成java.util.Date，升级成3.5.3以后，变成了Timestamp

#### 复现步骤
如上

#### 错误结果
如上

#### 期望结果
datetime类型字段能正确映射成java.util.Date

**Comment by lanjerry** [comment]
@liukai237 该问题已修复，具体查看此PR，目前可以先用类型转换器重写解决
https://github.com/baomidou/generator/pull/263
