### ISSUE TITLE
关于代码生成SQLserver 数据库的一些问题

### ISSUE THREAD

**Issue by leblog** [baomidou/generator#270]
请将问题描述清楚,别耽误彼此打(xi)工(jiao)赚(nen)钱(mo)的时间.
如果能直接提供错误示例,请上传仓库或私发邮箱,对于私发邮箱的代码,承诺不泄露来源方信息(邮箱名,公司名等信息),阅后即焚.

#### 版本信息

​	生成器版本: 3.5.3

​	数据库版本: sqlserver 2017

​	模板引擎版本: 

#### 问题详情

能出一个sqlserver 的代码生成的案列吗,我配置使用的3.5.3 不能生成
#### 复现步骤
![image](https://user-images.githubusercontent.com/56074493/191166428-a7a2c72b-6dc1-40d5-8c55-4c07c6bd28f7.png)

#### 错误结果
![image](https://user-images.githubusercontent.com/56074493/191166493-880fa401-40df-4ecd-bb41-3e62421f805b.png)
#### 期望结果
期望能有一个能用的sqlserver数据库的最佳实践

**Comment by lanjerry** [comment]
@leblog 驱动包有问题，排查下是不是SQL Server的驱动包跟JDK版本不适配
https://learn.microsoft.com/zh-cn/sql/connect/jdbc/download-microsoft-jdbc-driver-for-sql-server?view=sql-server-2017
