### ISSUE TITLE
为什么把Lombok @Data注解去掉了,   使用了@Getter@Setter代替?

### ISSUE THREAD

**Issue by lvdalian** [baomidou/generator#271]
#### 版本信息
​	生成器版本:  3.5.2
#### 问题详情
       为什么把Lombok @Data注解去掉了,   使用了@Getter@Setter代替?

**Comment by lanjerry** [comment]
@lvdalian 因为@Getter@Setter够用了

**Comment by tastypinenut** [comment]
> @lvdalian 因为@getter@Setter够用了

缺少了@ToString注解，entity.java.ftl中entityLombokModel=false时都会生成toString方法

**Comment by qmdx** [comment]
@Data 导致编译太慢 ，这是主要原因

> @lvdalian 因为@getter@Setter够用了
