### ISSUE TITLE
PG库无法生成字段

### ISSUE THREAD

**Issue by chenyuanyu-king** [baomidou/generator#276]
请将问题描述清楚,别耽误彼此打(xi)工(jiao)赚(nen)钱(mo)的时间.
如果能直接提供错误示例,请上传仓库或私发邮箱,对于私发邮箱的代码,承诺不泄露来源方信息(邮箱名,公司名等信息),阅后即焚.

#### 版本信息

​	生成器版本: 3.5.2

​	数据库版本: PostgreSQL 12.12, compiled by Visual C++ build 1914, 64-bit

​	模板引擎版本: freemarker 2.3.31

#### 问题详情
@Test
    public void generator() {
        FastAutoGenerator
                .create(new DataSourceConfig.Builder("jdbc:postgresql://localhost:5432/xx","xx","xx").schema("portal"))
                .globalConfig(builder -> {
                    builder.author("xx")
                            .fileOverride()
                            .disableOpenDir()
                            .enableSwagger()
                            .dateType(DateType.ONLY_DATE)
                            .commentDate("yyyy-MM-dd HH24:mm:ss")
                            .outputDir("E:\\Unit\\generator");
                })
                .packageConfig(builder -> {
                    builder.parent("xx.xx.adapter")
                            .moduleName(null)
                            .controller("controller")
                            .service("service")
                            .serviceImpl("service.impl")
                            .mapper("mapper")
                            .xml("mapper.xml")
                            .entity("model.atp");
                })
                .strategyConfig(builder -> {
                    builder.addTablePrefix("st_", "sys_")
                            .addTableSuffix("", "")
                            .addInclude(new String[]{
                                    "st_employee", "st_employee_login", "st_employee_mis",
                            })
                            .controllerBuilder()
                            .enableRestStyle()
                            .enableHyphenStyle()
                            .formatFileName("%sController")
                            .serviceBuilder()
                            .formatServiceFileName("%sService")
                            .formatServiceImplFileName("%sServiceImpl")
                            .mapperBuilder()
                            .enableMapperAnnotation()
                            .entityBuilder()
                            .enableTableFieldAnnotation()
                            .naming(NamingStrategy.underline_to_camel)
                            .columnNaming(NamingStrategy.underline_to_camel);
                })
                .templateEngine(new FreemarkerTemplateEngine())
                .execute();
    }
#### 错误结果
package smart.chengdu.login.adapter.model.atp;

import com.baomidou.mybatisplus.annotation.TableName;
import java.io.Serializable;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * <p>
 * 员工
 * </p>
 *
 * @author chenyuanyu
 * @since 2022-10-23 1124:44:50
 */
@TableName("st_employee")
@ApiModel(value = "Employee对象", description = "员工")
public class Employee implements Serializable {

    private static final long serialVersionUID = 1L;

    @Override
    public String toString() {
        return "Employee{" +
        "}";
    }
}

#### 期望结果

生成实体类中一个字段也没有

**Comment by lanjerry** [comment]
@chenyuanyu-king 有报错信息吗

**Comment by chenyuanyu-king** [comment]
没有任何报错信息，因此搞得我比较疑惑。。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "baomidou/generator"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月3日(星期四) 下午3:44
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [baomidou/generator] PG库无法生成字段 (Issue #276)





 
@chenyuanyu-king 有报错信息吗

**Comment by lanjerry** [comment]
@chenyuanyu-king 有线上的PG库，可以测试一下吗

**Comment by chenyuanyu-king** [comment]
抱歉抱歉，刚刚我重新运行了代码，现在可以生成字段了。。。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "baomidou/generator"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月3日(星期四) 下午3:48
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [baomidou/generator] PG库无法生成字段 (Issue #276)





 
@chenyuanyu-king 有线上的PG库，可以测试一下吗
