### ISSUE TITLE
likeTable 不起作用。

### ISSUE THREAD

**Issue by iamnewsea** [baomidou/generator#277]
3.5.2 的实体生成器：
我期望使用  .likeTable(new LikeTable("s_", SqlLike.LEFT)) ， 来过滤出 s_ 开头的表名， 但是它不起作用。

**Comment by lanjerry** [comment]
@iamnewsea 要过滤s_ 开头的表名，应该是new LikeTable("s_", SqlLike.RIGHT)

**Comment by lanjerry** [comment]
@iamnewsea 后面版本会改过来，现在的容易造成误解

**Comment by lanjerry** [comment]
@iamnewsea 先使用SQL语句查询方式，即.databaseQueryClass(SQLQuery.class)，默认查询方式已修复此功能，等后面发版，对应的PR：https://github.com/baomidou/generator/pull/280/commits/e2de540cf94798b32f1b91fa7ee3714fdec5af3b
