### ISSUE TITLE
后续是否考虑支持swagger3

### ISSUE THREAD

**Issue by ahaha-vip** [baomidou/generator#28]
如果能直接提供错误示例,请上传仓库或私发邮箱.

对于私发邮箱的代码,承诺不泄露来源方信息(邮箱名,公司名等信息),阅后即焚.

#### 生成器版本与模板引擎版本
mybatis-plus-version: 3.4.1
velocity-engine-version: 2.1

#### 错误信息
目前生成的代码只支持Swagger2，是否能提供支持OpenAPI 3.0 规范的swagger3

**Comment by ahaha-vip** [comment]
加个版本选择器呗，毕竟openApi3才是未来啊

**Comment by qmdx** [comment]
生成代码只是设计 annotation 部分 swagger 2 3 并没有差距

**Comment by ahaha-vip** [comment]
> 生成代码只是涉及 annotation 部分 swagger 2 3 并没有差距

Swagger3.0支持最新的OpenAPI标准，两者并不兼容，主流开发工具也有了OpenAPI3.0的相关支持，如IDEA、POSTMAN等。但如果只是做业务系统的CRUD接口描述的话确实没有差距。
https://support.smartbear.com/swaggerhub/docs/tutorials/openapi-3-tutorial.html

**Comment by AHBICJ** [comment]
OpenApi3 .0 注解真的完全不一样了 比如 springdoc-openapi

**Comment by ahaha-vip** [comment]
> OpenApi3 .0 注解真的完全不一样了 比如 springdoc-openapi

自定义模块生成吧
