### ISSUE TITLE
写文件时，文件的路径log日志丢失

### ISSUE THREAD

**Issue by xiaoyaozi-edu** [baomidou/generator#281]
引擎日志调整，commit 2d601fd，这次提交后，就没有日志输出了。
FreemarkerTemplateEngine不会调用父类AbstractTemplateEngine的writer方法，也就不会输出日志。
我使用的版本是3.5.2，是我使用错误吗？

**Comment by lanjerry** [comment]
@xiaoyaozi-edu 是指这个打印吗“logger.debug("模板:" + templatePath + ";  文件:" + outputFile);”？

**Comment by lanjerry** [comment]
@xiaoyaozi-edu  https://github.com/baomidou/generator/pull/283/commits/11d020d8572bd71b8901322fc25743fd63f5ad84

**Comment by zibuyuedu** [comment]
@lanjerry 是的，pr https://github.com/baomidou/generator/commit/11d020d8572bd71b8901322fc25743fd63f5ad84 这样改了之后就可以正常输出日志了：“logger.debug("模板:" + templatePath + "; 文件:" + outputFile);”。
这个问题可以关闭了。

**Comment by xiaoyaozi-edu** [comment]
@lanjerry 是的，pr https://github.com/baomidou/generator/commit/11d020d8572bd71b8901322fc25743fd63f5ad84 这样改了之后就可以正常输出日志了：“logger.debug("模板:" + templatePath + "; 文件:" + outputFile);”。
