### ISSUE TITLE
mybatis plus 支持枚举转 数字活字符串存数据库，为啥生成code这里不支持自定义字段使用枚举类型呢

### ISSUE THREAD

**Issue by wangwengeek** [baomidou/generator#285]
#### 问题详情
mybatis plus 支持枚举转 数字活字符串存数据库，为啥生成code这里不支持自定义字段使用枚举类型呢
#### 期望结果
生成code 支持某个表的某个字段生成类型是自定义枚举

**Comment by lanjerry** [comment]
@wangwengeek 这个支持不了，你每个字段对应的枚举都是未知的，目前只能通过重写获取字段类型时，再根据你的字段，赋值对应的枚举

**Comment by wangwengeek** [comment]
<img width="1316" alt="image" src="https://user-images.githubusercontent.com/22323822/205024833-13dbb40f-d74e-4337-a791-2b49ead9f703.png">

<img width="1308" alt="image" src="https://user-images.githubusercontent.com/22323822/205024977-2e99ea48-54b1-40b4-9b28-0f49b6737807.png">
<img width="842" alt="image" src="https://user-images.githubusercontent.com/22323822/205025039-4c77e9bd-f637-4e76-b011-88a3cd9447f4.png">
类似这样扩展下呢

**Comment by lanjerry** [comment]
@wangwengeek 目前不考虑你这种写法，感谢建议。
