### ISSUE TITLE
3.5.3 enableSpringdoc 实体类上表名注释 $!{table.comment}

### ISSUE THREAD

**Issue by luoyongsir** [baomidou/generator#287]
请将问题描述清楚,别耽误彼此打(xi)工(jiao)赚(nen)钱(mo)的时间.
如果能直接提供错误示例,请上传仓库或私发邮箱,对于私发邮箱的代码,承诺不泄露来源方信息(邮箱名,公司名等信息),阅后即焚.

#### 版本信息

​	生成器版本: 3.5.3

​	数据库版本: mysql 8

​	模板引擎版本:  ftl

#### 问题详情
实体类上表名注释未获取到，还是 $!{table.comment}
#### 复现步骤
 enableSpringdoc 
#### 错误结果
 $!{table.comment}
#### 期望结果
真实表注释

**Comment by lanjerry** [comment]
@luoyongsir 提供下SQL脚本，我这边测试是OK的
