### ISSUE TITLE
sql2008数据库代码生成entity和mapper.xml的字段属性全部变为小写了

### ISSUE THREAD

**Issue by gmshiot** [baomidou/generator#31]
如果能直接提供错误示例,请上传仓库或私发邮箱.

对于私发邮箱的代码,承诺不泄露来源方信息(邮箱名,公司名等信息),阅后即焚.

#### 生成器版本与模板引擎版本
生成器版本3.4.1  模板引擎版本FreemarkerTemplateEngine

#### 复现步骤
建一个字段同时包含有大小写的表，即可复现

**Comment by nieqiurong** [comment]
1.补充代码策略配置.
2.不出错误值与期望结果.

**Comment by gmshiot** [comment]
策略配置如下：
strategy.setColumnNaming(NamingStrategy.underline_to_camel);
	       //自定义继承的Entity类全称，带包名
	       strategy.setSuperEntityClass("com.bq.common.entity.BaseEntity");
	       //自定义基础的Entity类，公共字段
	       //strategy.setSuperEntityColumns("id");
	       //【实体】是否为lombok模型（默认 false）
	       strategy.setEntityLombokModel(true);
	       //【实体】是否为builder模型（默认 false）
	       strategy.setChainModel(true);
比如：字段名称为createTime,则生成的为createtime,期望结果：如果字段不包含下划线，则与字段名称相同，既createTime,如果有下划线则生成驼峰模式的属性名。
