### ISSUE TITLE
公共字段调试结果不一致

### ISSUE THREAD

**Issue by qq329401134** [baomidou/generator#34]
#### 生成器版本与模板引擎版本
3.4.1

#### 错误信息
未报错，在判断公共字段的代码中出现异常
一个断点的时候重新运行了三次都是41个字段，0个公共，当两个断点的时候运行发现竟然是37个字段4个公共字段
未知原因

#### 复现步骤
![不懂](https://user-images.githubusercontent.com/38587734/103399412-ff3a3f00-4b7b-11eb-82cb-f5288610eb30.gif)

**Comment by qq329401134** [comment]
3.4.0 是对的   3.4.1有点坑 ，它的StrategyConfig里面的代码有点问题

**Comment by nieqiurong** [comment]
已3.5.0-SNAPSHOT为准.
