### ISSUE TITLE
3.5.0的版本在中央仓库有吗？目前在仓库只能看到3.4.1

### ISSUE THREAD

**Issue by Zoe-Z1** [baomidou/generator#35]
#### 版本信息

​	生成器版本: 3.4.1

​	数据库版本: mysql 8.0

​	模板引擎版本:  velocity2.2

#### 问题详情
3.5.0的版本在中央仓库有吗？目前在仓库只能看到3.4.1

**Comment by nieqiurong** [comment]
暂时没有发布,只有使用快照版本的,3.5.0-SNAPSHOT.

**Comment by mostcool** [comment]
> 暂时没有发布,只有使用快照版本的,3.5.0-SNAPSHOT.

怎么引用到3.5.0-SNAPSHOT？

**Comment by lanjerry** [comment]
@mostcool 
<repository>
      <id>snapshot</id>
      <name>mp-snapshot</name>
      <url>https://oss.sonatype.org/content/repositories/snapshots/</url>
      <snapshots>
          <enabled>true</enabled>
      </snapshots>
  </repository>

**Comment by ye17186** [comment]
![image](https://user-images.githubusercontent.com/33926823/109098458-57e11f00-775c-11eb-8772-ed998938e902.png)
mybatis-plus官网写的让引入3.4.2版本，怎么这个版本也没有发布呢

**Comment by lanjerry** [comment]
@ye17186 写错了，现在只有3.4.1版本

**Comment by 2534999** [comment]
3.5.0 什么时候发布呀，等的好焦急

**Comment by mengweijin** [comment]
期待 3.5.0 早日发布
