### ISSUE TITLE
Kingbase代码生成的时候没有查到表注释

### ISSUE THREAD

**Issue by Eveamu** [baomidou/generator#4]
### 当前使用版本(必填,否则不予处理)
3.3.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
请使用表user_tab_comments和user_col_comments来查询表注释和表字段注释

### 重现步骤(如果有就写完整)
无

### 报错信息
无

**Comment by qmdx** [comment]
非主流数据只接受pr
