### ISSUE TITLE
请问generator代码时，如何自动为createtime和updatetime生成@TableField注解

### ISSUE THREAD

**Issue by hdtopku** [baomidou/generator#40]
请将问题描述清楚,别耽误彼此打(xi)工(jiao)赚(nen)钱(mo)的时间.
如果能直接提供错误示例,请上传仓库或私发邮箱,对于私发邮箱的代码,承诺不泄露来源方信息(邮箱名,公司名等信息),阅后即焚.

#### 版本信息

​	生成器版本:3.4.1

​	数据库版本:mysql:5.7

​	模板引擎版本:2.3.28

#### 问题详情
想使用createtime和updatetime字段自动填充功能，可是generator模板配置没找到方法
```
@TableField(value = "create_time", fill = FieldFill.INSERT)
```
#### 复现步骤
在creatime和updatetime手动填充@TableField注解，很不方便，而且后期可能被覆盖。
#### 期望结果
如何在自动生成代码的时候，creatime和updatetime自动填充@TableField注解，达到createtime和updatetime自动更新的目的

**Comment by lanjerry** [comment]
@hdtopku 
自动填充在策略配置里面
3.4.1：
StrategyConfig strategy = new StrategyConfig();
strategy.setTableFillList(Collections.singletonList(new TableFill("create_time", FieldFill.INSERT)));
3.5.0-SNAPSHOT：
return new StrategyConfig.Builder()
	.entityBuilder()
	.addTableFills(new Column("create_time", FieldFill.INSERT)) //字段模式
	.addTableFills(new Property("updateTime", FieldFill.INSERT_UPDATE)) //属性模式
	.build();

**Comment by kiritokun07** [comment]
> @hdtopku 自动填充在策略配置里面 3.4.1版本： StrategyConfig strategy = new StrategyConfig(); strategy.setTableFillList(Collections.singletonList(new TableFill("create_time", FieldFill.INSERT))); 3.5.0-SNAPSHOT快照版本： new StrategyConfig.Builder() .entityBuilder() .addTableFills(new Column("create_time", FieldFill.INSERT)) //字段模式 .addTableFills(new Property("updateTime", FieldFill.INSERT_UPDATE)) //属性模式 .build();

请问addTableFills是否有添加过滤条件的能力，如只有`date_time`类型的字段才添加相应注解
