### ISSUE TITLE
建议配置里面可以设置生成的实体类字段列有注释(采用数据库注释)以及注释的前缀:用于提示区分用

### ISSUE THREAD

**Issue by jf11480** [baomidou/generator#44]
请将问题描述清楚,别耽误彼此打(xi)工(jiao)赚(nen)钱(mo)的时间.
如果能直接提供错误示例,请上传仓库或私发邮箱,对于私发邮箱的代码,承诺不泄露来源方信息(邮箱名,公司名等信息),阅后即焚.

#### 版本信息

​	生成器版本: 3.4.1

​	数据库版本:无

​	模板引擎版本: velocity2.2

#### 问题详情
生成的实体类字段列有注释(采用数据库注释)以及注释的前缀:用于提示区分用
#### 复现步骤
无
#### 错误结果
无
#### 期望结果
建议加在配置里面
生成的实体类字段列有注释(采用数据库注释)以及注释的前缀:用于提示区分用
目前可以倒是可以通过修改模板,和注入map实现

**Comment by qmdx** [comment]
请自己实现个性需求
