### ISSUE TITLE
生成时如何设置某字段只从数据库获取新增或修改时忽略该字段

### ISSUE THREAD

**Issue by BlackKongo** [baomidou/generator#46]
请将问题描述清楚,别耽误彼此打(xi)工(jiao)赚(nen)钱(mo)的时间.
如果能直接提供错误示例,请上传仓库或私发邮箱,对于私发邮箱的代码,承诺不泄露来源方信息(邮箱名,公司名等信息),阅后即焚.

#### 版本信息

​	生成器版本:3.4.1

​	数据库版本:SQL Server 13.0.5026.0

​	模板引擎版本:freemarker 2.2.30

#### 问题详情

连接sqlserver数据生成代码时，表字段类型为timestamp。
但是该列在sqlserver中为相当与一个版本记录，新增或者修改时都会自动的进行更新，不能通过外部进行修改。
执行更新方法时出现错误不能更新时间戳列。
如果把该列设置为setSuperEntityColumns 不生成该字段可以解决这个问题，
但是如果设置BaseResultMap=true和BaseColumnList=true时，
会发现生成的mapper文件中还存在此列，这时查询会导致报错。
#### 复现步骤
![image](https://user-images.githubusercontent.com/44402336/108712920-75db3380-7552-11eb-9595-1207f9b25e81.png)
![image](https://user-images.githubusercontent.com/44402336/108712973-88ee0380-7552-11eb-98a0-471faf1d7fb5.png)
![image](https://user-images.githubusercontent.com/44402336/108712999-93a89880-7552-11eb-96e2-b462ce64f8de.png)
![image](https://user-images.githubusercontent.com/44402336/108713020-999e7980-7552-11eb-8771-d5c68294d9ee.png)

#### 错误结果
![image](https://user-images.githubusercontent.com/44402336/108713056-a58a3b80-7552-11eb-86cc-a26cbb5efbc0.png)

#### 期望结果
要如何进行设置。

**Comment by qmdx** [comment]
https://github.com/baomidou/generator/commit/ea642dd070c0c1e8a2d8429623947c4156132c9c
