### ISSUE TITLE
请问只需要entity文件该怎么设置，mapper其他的不需要

### ISSUE THREAD

**Issue by ChunSource** [baomidou/generator#47]
请将问题描述清楚,别耽误彼此打(xi)工(jiao)赚(nen)钱(mo)的时间.
如果能直接提供错误示例,请上传仓库或私发邮箱,对于私发邮箱的代码,承诺不泄露来源方信息(邮箱名,公司名等信息),阅后即焚.

#### 版本信息

​	生成器版本:

​	数据库版本:

​	模板引擎版本:

**Comment by star4j** [comment]
![image](https://user-images.githubusercontent.com/25194485/109778508-ddbf0780-7c3f-11eb-8793-586e1f1adb0e.png)

**Comment by qmdx** [comment]
disable
