### ISSUE TITLE
mybatis-plus代码生成器，希望生成的imports按ASCII码排序

### ISSUE THREAD

**Issue by forfuns** [baomidou/generator#51]
请将问题描述清楚,别耽误彼此打(xi)工(jiao)赚(nen)钱(mo)的时间.
如果能直接提供错误示例,请上传仓库或私发邮箱,对于私发邮箱的代码,承诺不泄露来源方信息(邮箱名,公司名等信息),阅后即焚.

#### 版本信息

​	生成器版本: 3.4.1

​	数据库版本: 没要求

​	模板引擎版本: 没要求

#### 问题详情

我们在根据我们的项目编写实体生成器，但我们的项目有`CheckStyle`，其中一条规则会自动检查import的包有没有按照ASCII码排序排序，希望可以在生成器这块一步到位，我看了一下代码，大概是在:

com.baomidou.mybatisplus.generator.config.po.TableInfo#importPackages 这个属性改成 TreeSet 即可？

可以加入这个feature码？

**Comment by forfuns** [comment]
为啥没人理我了啊？？？？？？？？？

**Comment by forfuns** [comment]
sad

**Comment by qmdx** [comment]
https://github.com/baomidou/generator/commit/d0c349f1d3ea94676e24b1c1503341f6fbaca1e4
