### ISSUE TITLE
数据库字段是TestUser这样的形式，希望生成Entity时能将首字母转换为小写，要不然EasyExecl无法使用。

### ISSUE THREAD

**Issue by ijry** [baomidou/generator#52]
数据库字段是TestUser这样的形式，希望生成Entity时能将首字母转换为小写，要不然EasyExecl无法使用。能不能增加一个这样的配置。

**Comment by qmdx** [comment]
自定义模板处理

**Comment by ijry** [comment]
> 自定义模板处理

自定义模板？模板不是只是个基础结构吗，字段名称的大小写规则还能再模板里定义？

**Comment by ijry** [comment]
我指的是这个NamingStrategy.underline_to_camel，能不能加一个，自动将首字母转小写的配置。这模板咋实现？
