### ISSUE TITLE
请问我生成的Entity .关键字没有@tableid 注解. 

### ISSUE THREAD

**Issue by samrtian** [baomidou/generator#55]
#### 版本信息

​	生成器版本: 3.4.1

​	数据库版本:  阿里云 mysql

​	模板引擎版本:  Beelt 默认模板

#### 问题详情
```
public class XUserinfo implements Serializable {
    private static final long serialVersionUID = 1L;
    /// 这里是数据库表主键 email .但是没有 @tableid 注解..
   /// 并且复制到项目中使用的时候.提示
  /// Can not find table primary key in Class: "com.yokopos.dao.entity.XUserinfo".
    @ApiModelProperty(value = "用户id")
    private String email;

    @ApiModelProperty(value = "pos登录id")
    @TableField("posId")
    private String posid;

    @TableField("firstName")
    private String firstname;
}
```

我也没有设置公共id 
strategy.setSuperEntityColumns("id");

请问是配置问题吗

**Comment by qmdx** [comment]
默认 名字为 id 作为主键，非 id 命名会根据数据库配置主键自动注解，无注解不处理  setSuperEntityColumns 是公共实体设置为 id

**Comment by samrtian** [comment]
> 默认 名字为 id 作为主键，非 id 命名会根据数据库配置主键自动注解，无注解不处理 setSuperEntityColumns 是实体父类设置为 id 不需要重复生成申明

好的。。谢谢你。还有一个情况是在springboot启动的时候。
会提示xxxx 实体类没有找到主键id 。因为这些实体类是联合主键。
但是对整体程序没有任何影响可以正常使用。 怎么解决这些提示呢。手动的话在实体类上边加主键注解应该可以解决。如果让生成器自动给联合主键加主键是不是还没有这个功能呢？
