### ISSUE TITLE
多模块项目配置文件生成路径

### ISSUE THREAD

**Issue by dale19900108** [baomidou/generator#58]
#### 版本信息

​	生成器版本:  3.4.1

​	数据库版本:  这不重要

​	模板引擎版本:  这也不重要

#### 问题详情
多模块项目的时候，需要生成到不同模块下，所以需要配置下packageConfig来调整对应生成位置，但是这个packageConfig，里面的map是私有，想单独指定，就只能通过反射，然后set。有点不方便。

是我的使用方法不正确么？有没有更方便的方法应对此场景？

**Comment by dale19900108** [comment]
刚才实验了3.5.0的貌似也是一样的问题，无法指定具体文件的位置，不知道是不是我配置的不正确~如果有解决办法可以回复我下~谢谢。

**Comment by qmdx** [comment]
`3.5.0`  参考 https://github.com/baomidou/generator/blob/develop/mybatis-plus-generator/src/test/java/com/baomidou/mybatisplus/test/generator/H2CodeGenerator.java 注入处理，修改文件输出目录试试，更多欢迎 pr
