### ISSUE TITLE
重写initTableMap方法后，batchOutput方法内，应当在getObjectMap之前先调用initTableMap

### ISSUE THREAD

**Issue by admintertar** [baomidou/generator#63]
#### 版本信息

​	生成器版本: 3.4.2

​	数据库版本:mysql5.6

​	模板引擎版本:默认引擎

#### 问题详情

想要在生成的entity类里面增加后缀 Bo

#### 复现步骤

![image](https://user-images.githubusercontent.com/29689362/118086833-255bcf80-b3f7-11eb-8a2f-bcdf81b34419.png)

![image](https://user-images.githubusercontent.com/29689362/118086440-90f16d00-b3f6-11eb-9eb4-e82141cf4bf8.png)

**Comment by qmdx** [comment]
注入 INameConvert  修改实体名 https://github.com/baomidou/generator/blob/develop/mybatis-plus-generator/src/main/java/com/baomidou/mybatisplus/generator/config/INameConvert.java
