### ISSUE TITLE
如何自定义mapper.xml文件名和生成位置？

### ISSUE THREAD

**Issue by mostcool** [baomidou/generator#65]
#### 版本信息

​	生成器版本: 3.5.0

​	数据库版本: mysql 8.0

​	模板引擎版本: freemarker

#### 问题详情
如何自定义mapper.xml文件名和生成位置？

原来是通过InjectionConfig来实现的，在3.5.0中如何使用呢？
```java
new InjectionConfig()
                .addFileOutConfig(new FileOutConfig("/templates/mapper.xml.ftl") {
                    @Override
                    public File outputFile(TableInfo tableInfo) {
                        return new File(projectPath + "/src/main/resources/mapper/" + tableInfo.getEntityName() + "DAO.xml");
                    }
                });
```

#### 期望结果
期望能实现自定义mapper.xml文件名和生成位置

**Comment by xie-fei** [comment]
同问，如何自定义mapper.xml的文件位置

**Comment by qmdx** [comment]
https://github.com/baomidou/generator/blob/develop/mybatis-plus-generator/src/test/java/com/baomidou/mybatisplus/test/generator/H2CodeGenerator.java   等下一个版本按照这个方式配置

**Comment by fanlei1988** [comment]
@qmdx 希望 能在ConfigBuilder 开放pathInfo 属性set的能力，最大限度的利用原有的路径解析能力

**Comment by lanjerry** [comment]
使用至少最新3.5.1版本
mapper.xml文件名：参考H2CodeGeneratorTest->testCustomTemplateName
生成位置：参考H2CodeGeneratorTest->testCustomTemplatePath
