### ISSUE TITLE
实体模板默认生成注释，建议可控制

### ISSUE THREAD

**Issue by Yeahfun** [baomidou/generator#66]
请将问题描述清楚,别耽误彼此打(xi)工(jiao)赚(nen)钱(mo)的时间.
如果能直接提供错误示例,请上传仓库或私发邮箱,对于私发邮箱的代码,承诺不泄露来源方信息(邮箱名,公司名等信息),阅后即焚.

#### 版本信息

​	生成器版本: 3.5.0

​	数据库版本: 

​	模板引擎版本: freemarker

#### 问题详情
![1622446077(1)](https://user-images.githubusercontent.com/35020712/120156856-fc27a580-c224-11eb-9c20-52744b39ddba.jpg)

**Comment by lanjerry** [comment]
@Yeahfun 控制啥，举例下
