### ISSUE TITLE
生成实体，建议排序字段，可以生成@OrderBy注解

### ISSUE THREAD

**Issue by Yeahfun** [baomidou/generator#69]
请将问题描述清楚,别耽误彼此打(xi)工(jiao)赚(nen)钱(mo)的时间.
如果能直接提供错误示例,请上传仓库或私发邮箱,对于私发邮箱的代码,承诺不泄露来源方信息(邮箱名,公司名等信息),阅后即焚.

#### 版本信息

​	生成器版本: 3.5.0

​	数据库版本:

​	模板引擎版本:

#### 问题详情
建议可以生成@OrderBy注解

**Comment by lanjerry** [comment]
暂不考虑，可自定义模板处理
