### ISSUE TITLE
3.5.0 生成的实体类 pkVal方法 尝试分配较弱的访问权限

### ISSUE THREAD

**Issue by MZHY08** [baomidou/generator#70]
#### 版本信息

​	生成器版本: 3.5.0

#### 问题详情
新生成器生成的实体类中的pkVal方法，父类为public，而生成的子类是protected
@Override
protected Serializable pkVal() {
    return this.id;
}

**Comment by guyinsheng** [comment]
模板文件里也没有引入Serializable的包，会导致生成的文件有包缺失

**Comment by qmdx** [comment]
https://github.com/baomidou/generator/commit/8416d14e00c7d047e69884a858df31a5b8ebc379
