### ISSUE TITLE
3.5.0 XML无法生成到指定位置

### ISSUE THREAD

**Issue by JaydenLaw** [baomidou/generator#72]
请将问题描述清楚,别耽误彼此打(xi)工(jiao)赚(nen)钱(mo)的时间.
如果能直接提供错误示例,请上传仓库或私发邮箱,对于私发邮箱的代码,承诺不泄露来源方信息(邮箱名,公司名等信息),阅后即焚.

#### 版本信息

​	生成器版本:  3.5.0
### 
​	数据库版本:

​	模板引擎版本:

#### 复现步骤  在PathInfoHandler类的构造函数中
putPathInfo(templateConfig.getXml(), ConstVal.XML_PATH, ConstVal.MAPPER); 
使用了MAPPER常量，正确应该是ConstVal.XML才对。

**Comment by ricardo0624** [comment]
3.5.0的tag都没打

**Comment by kiritokun07** [comment]
ps追问：如果想设定xml输出路径为resources/mapper，应该怎么设置PackageConfig.Builder().xml()

**Comment by chenmaochang** [comment]
我也有这样的困惑

**Comment by chenmaochang** [comment]
然后我用反射去操作了pathInfo,手动替换掉了xml的生成地址,太不优雅了,快点修复吧

**Comment by suning4583** [comment]
![image](https://user-images.githubusercontent.com/12489065/127009353-c4a8bd23-f9c8-48cd-8bac-69ffc6b12d5a.png)
![image](https://user-images.githubusercontent.com/12489065/127009435-eedd5810-ffa1-4eee-b5fe-27de0e2cc6ca.png)
![image](https://user-images.githubusercontent.com/12489065/127009496-3e7274b5-8874-40e9-8ec1-6cbc6881f0d3.png)
![image](https://user-images.githubusercontent.com/12489065/127009927-a6e796aa-e8d4-4bf7-ae3b-b3e5b1877a01.png)

**Comment by lanjerry** [comment]
@JaydenLaw 
使用至少3.5.1版本
参考H2CodeGeneratorTest->testCustomTemplatePath
