### ISSUE TITLE
默认模板统一换行符

### ISSUE THREAD

**Issue by ztyzbb** [baomidou/generator#73]
请将问题描述清楚,别耽误彼此打(xi)工(jiao)赚(nen)钱(mo)的时间.
如果能直接提供错误示例,请上传仓库或私发邮箱,对于私发邮箱的代码,承诺不泄露来源方信息(邮箱名,公司名等信息),阅后即焚.

#### 版本信息

​	生成器版本:3.5.0

​	数据库版本:

​	模板引擎版本:2.3.31

#### 问题详情

使用生成器自带模板生成代码时生成出来的文件，有些是LF换行符，有些是CRLF换行符，检查后发现生成器内自带模板文件的换行符不统一，建议统一为LF

**Comment by qmdx** [comment]
https://github.com/baomidou/generator/commit/934f631a9f5b6ed6949f517ffba3a3d08c6d98ec
