### ISSUE TITLE
springboot2 多模块的情况怎么填写自定义模板的路径

### ISSUE THREAD

**Issue by lyhisphper** [baomidou/generator#74]
![image](https://user-images.githubusercontent.com/29226053/122024850-63d01a00-cdfb-11eb-9b7c-35fd3353efe3.png)

填写 ”templates/controller.java“ ，”src/main/resources/templates/controller.java“ 都不行

**Comment by lanjerry** [comment]
@lyhisphper 
使用至少3.5.1版本
参考H2CodeGeneratorTest->testCustomTemplate
