### ISSUE TITLE
如何在生成代码的时候生成jsr303的validator代码？

### ISSUE THREAD

**Issue by anicething** [baomidou/generator#77]
请将问题描述清楚,别耽误彼此打(xi)工(jiao)赚(nen)钱(mo)的时间.
如果能直接提供错误示例,请上传仓库或私发邮箱,对于私发邮箱的代码,承诺不泄露来源方信息(邮箱名,公司名等信息),阅后即焚.

#### 版本信息

​	生成器版本:

​	数据库版本:

​	模板引擎版本:

**Comment by qmdx** [comment]
自定义模板
