### ISSUE TITLE
如何添加自定义模板？

### ISSUE THREAD

**Issue by 1308207524** [baomidou/generator#78]
请将问题描述清楚,别耽误彼此打(xi)工(jiao)赚(nen)钱(mo)的时间.
如果能直接提供错误示例,请上传仓库或私发邮箱,对于私发邮箱的代码,承诺不泄露来源方信息(邮箱名,公司名等信息),阅后即焚.

#### 版本信息

​	生成器版本:3.5.0

​	数据库版本:

​	模板引擎版本:ftl

#### 问题详情
![image](https://user-images.githubusercontent.com/34747325/122242679-1be1ed80-cef6-11eb-9fd0-d01230a2a9ad.png)

这里只能输出controller，service，mapper吗？如果我想生成其他模板，比如我写了一个query.ftl模板文件，如何配置

**Comment by 923391410** [comment]
官方在这里没有做支持，但如果要增加自定义模板的话，完全可以通过继承模板引擎相关类来实现，实现起来代码也并不复杂。
直接继承某个模板引擎类如：**FreemarkerTemplateEngine**，然后重载`batchOutput()`方法，在这个方法里面调用`outputFile()`方法来生成其他文件即可。

**Comment by 923391410** [comment]
@xie-fei

**Comment by xie-fei** [comment]
> @xie-fei

**Comment by xie-fei** [comment]
> 官方在这里没有做支持，但如果要增加自定义模板的话，完全可以通过继承模板引擎相关类来实现，实现起来代码也并不复杂。
> 直接继承某个模板引擎类如：**FreemarkerTemplateEngine**，然后重载`batchOutput()`方法，在这个方法里面调用`outputFile()`方法来生成其他文件即可。

谢谢，可以生成，只是略有点麻烦

**Comment by jerryzhengsz** [comment]
@xie-fei  怎么生成的,能告诉方法吗?谢谢.

**Comment by DaveRoey** [comment]
试试这样呢

            @Override
            public AbstractTemplateEngine templateEngine() {
                return new FreemarkerTemplateEngine() {
                    @Override
                    public AbstractTemplateEngine batchOutput() {
                        AbstractTemplateEngine abstractTemplateEngine = super.batchOutput();
                        ConfigBuilder config = this.getConfigBuilder();
                        config.getTableInfoList()
                                .forEach(e -> {

                                });
                        return abstractTemplateEngine;
                    }
                };

**Comment by lanjerry** [comment]
@1308207524 
使用至少3.5.1版本
参考H2CodeGeneratorTest->testCustomFile
