### ISSUE TITLE
3.5.0 版本的发布，README.md 这文档是认真的吗？😂

### ISSUE THREAD

**Issue by calvinit** [baomidou/generator#79]
文档错漏百出，要么发布版本的代码不是最新的，要么文档是旧的甚至是错的，就举一个其中例子来说好了，如下图：

<img width="817" alt="bug" src="https://user-images.githubusercontent.com/27403411/122369572-e4744f00-cf90-11eb-8112-ec03c1836d12.png">

这个 builder 哪里有这些方法？

<img width="540" alt="bug2" src="https://user-images.githubusercontent.com/27403411/122369851-27362700-cf91-11eb-8a9f-b53ee0cc8f6a.png">

#### 版本信息

​	生成器版本: 3.5.0

​	数据库版本: mysql 5.x

​	模板引擎版本: 默认

#### 问题详情

如上方描述。

#### 复现步骤

按文档说明，自定义配置。

#### 错误结果

无法使用。

#### 期望结果

正常使用。

**Comment by xml4cn** [comment]
哈哈，是的下面每个里都有错，我看是API改了，设置了很多默认值，文档还没改。
等跑通了，发个demo出来。

**Comment by TobiZh** [comment]
@Override
    protected Serializable pkVal() {
        return this.id;
    }
生成后 没有导入Serializable包，protected 得改成public

**Comment by AaronChen2012** [comment]
发布的版本跟源码是不一样的，文档也有问题

**Comment by qmdx** [comment]
在改版，完成后会调整
