### ISSUE TITLE
为何仓库里3.5.0-SNAPSHOT没了?

### ISSUE THREAD

**Issue by xianzheTM** [baomidou/generator#80]
不懂作者意思，3.5.0.1-SNAPSHOT出来了，3.5.0-SNAPSHOT为什么要去掉？

**Comment by lanjerry** [comment]
@xianzheTM 可直接升级至3.5.0正式版本
      <dependency>
          <groupId>com.baomidou</groupId>
          <artifactId>mybatis-plus-generator</artifactId>
          <version>3.5.0</version>
      </dependency>
