### ISSUE TITLE
3.5.0 无法指定xml生成目录，且service跟serviceImpl强关联绑定，不能自定义只生成service或serviceImpl了

### ISSUE THREAD

**Issue by binglang2** [baomidou/generator#81]
请将问题描述清楚,别耽误彼此打(xi)工(jiao)赚(nen)钱(mo)的时间.
如果能直接提供错误示例,请上传仓库或私发邮箱,对于私发邮箱的代码,承诺不泄露来源方信息(邮箱名,公司名等信息),阅后即焚.

#### 版本信息

​	生成器版本: 3.5.0

​	数据库版本: mysql 8.0

​	模板引擎版本: velocity 2.1

#### 问题详情
一、3.5.0 无法指定 xml 生成目录
二、service跟 serviceImpl 强关联绑定，不能自定义只生成 service 或 serviceImpl 了
![image](https://user-images.githubusercontent.com/25217458/123059806-ba150c80-d43c-11eb-897d-2a06fad44c7d.png)
如图，我自定义的模版里只需要生成 serviceImpl ，不需要生成 service，但是这个强绑定关系无法实现这个效果

#### 期望结果
1. 可以指定 xml 生成目录
2. 可以自定义只生成 service 或 serviceImpl ，而不是两个强关联必须都生成或都不生成

**Comment by makanglei1994** [comment]
```java
PathInfoHandler(GlobalConfig globalConfig, TemplateConfig templateConfig, PackageConfig packageConfig) {
    this.outputDir = globalConfig.getOutputDir();
    this.packageConfig = packageConfig;
    Map<String, String> pathInfo = packageConfig.getPathInfo();
    if (CollectionUtils.isNotEmpty(pathInfo)) {
        this.pathInfo.putAll(pathInfo);
    } else {
        this.putPathInfo(templateConfig.getEntity(globalConfig.isKotlin()), "entity_path", "Entity");
        this.putPathInfo(templateConfig.getMapper(), "mapper_path", "Mapper");
        this.putPathInfo(templateConfig.getXml(), "xml_path", "Mapper");
        this.putPathInfo(templateConfig.getService(), "service_path", "Service");
        this.putPathInfo(templateConfig.getServiceImpl(), "service_impl_path", "ServiceImpl");
        this.putPathInfo(templateConfig.getController(), "controller_path", "Controller");
    }
}
```
是不是module写错了？

**Comment by catch6** [comment]
@makanglei1994 很可能是写错了，源码里有XML 的常量，却在putPathInfo里写了 Mapper
![image](https://user-images.githubusercontent.com/15259698/125199552-4aef4300-e299-11eb-828b-7780d878d161.png)
![image](https://user-images.githubusercontent.com/15259698/125199569-58a4c880-e299-11eb-9713-6b450a7bf33d.png)

**Comment by lanjerry** [comment]
@binglang2 
使用至少3.5.1版本
自定义mapper.xml文件名：参考H2CodeGeneratorTest->testCustomTemplateName
已取消service跟serviceImpl强关联绑定，可生成其中一个，使用templateConfig的disable方法即可
