### ISSUE TITLE
strategyConfigBuilder.entityBuilder().enableTableFieldAnnotation() 开启生成实体时生成字段注解 配置无效

### ISSUE THREAD

**Issue by Max-Qiu** [baomidou/generator#82]
请将问题描述清楚,别耽误彼此打(xi)工(jiao)赚(nen)钱(mo)的时间.
如果能直接提供错误示例,请上传仓库或私发邮箱,对于私发邮箱的代码,承诺不泄露来源方信息(邮箱名,公司名等信息),阅后即焚.

#### 版本信息

​	生成器版本:
3.5.0
​	数据库版本:
MySQL8.0
​	模板引擎版本:
velocity2.2

#### 问题详情

strategyConfigBuilder.entityBuilder().enableTableFieldAnnotation()
开启生成实体时生成字段注解 无效
普通的字段缺少`@TableField`注解

PS：该功能在旧版本的`strategyConfig.setEntityTableFieldAnnotationEnable(true);`可以正常使用

#### 复现步骤

1. strategyConfigBuilder.entityBuilder().enableTableFieldAnnotation()
2. 运行autoGenerator.execute();
3. 查看实体字段

#### 错误结果

```java
    /**
     * 邮箱
     */
    private String email;
```

#### 期望结果

```java
    /**
     * 邮箱
     */
    @TableField("email")
    private String email;
```

**Comment by lanjerry** [comment]
@Max-Qiu 已修复，使用使用至少3.5.1版本
