### ISSUE TITLE
请问3.5后,如何实现自定义模版和自定义生成位置呢?

### ISSUE THREAD

**Issue by yuxicun** [baomidou/generator#85]
请问3.5后,如何实现自定义模版和自定义生成位置呢?就是除了正常的java,我想生成html静态文件的模版

**Comment by DaveRoey** [comment]
同问， 没有FileOutConfig类了。

**Comment by DaveRoey** [comment]
这样好像可以 
@Override
            public AbstractTemplateEngine templateEngine() {
                return new FreemarkerTemplateEngine() {
                    @Override
                    public AbstractTemplateEngine batchOutput() {
                        AbstractTemplateEngine abstractTemplateEngine = super.batchOutput();
                        ConfigBuilder config = this.getConfigBuilder();
                        config.getTableInfoList()
                                .forEach(e -> {
                                  
                                });
                        return abstractTemplateEngine;
                    }
                };
            }

**Comment by DaveRoey** [comment]
@Override
            public AbstractTemplateEngine templateEngine() {
                return new FreemarkerTemplateEngine() {
                    @Override
                    public AbstractTemplateEngine batchOutput() {
                        AbstractTemplateEngine abstractTemplateEngine = super.batchOutput();
                        ConfigBuilder config = this.getConfigBuilder();
                        config.getTableInfoList()
                                .forEach(e -> {

                                });
                        return abstractTemplateEngine;
                    }
                };

**Comment by mengweijin** [comment]
自定义模版和自定义生成位置，我是自己写了一个，不知道有没有更好的方式。
https://gitee.com/mengweijin/code-generator-maven-plugin/blob/master/src/main/java/com/github/mengweijin/generator/CustomerAutoGenerator.java
```java  
@Override
public IConfigBuilder<InjectionConfig> injectionConfigBuilder() {
    return new InjectionConfig.Builder().beforeOutputFile((tableInfo, objectMap) -> {
        FileOutput.outputFile(tableInfo, objectMap, this);
    });
}
```  
https://gitee.com/mengweijin/code-generator-maven-plugin/blob/master/src/main/java/com/github/mengweijin/generator/config/FileOutput.java

**Comment by lanjerry** [comment]
@yuxicun 
使用至少3.5.1版本
自定义模板：参考H2CodeGeneratorTest->testCustomTemplate
自定义生成位置：参考H2CodeGeneratorTest->testCustomTemplatePath
