### ISSUE TITLE
建议：模板文件的换行符统一修改为 LF

### ISSUE THREAD

**Issue by Max-Qiu** [baomidou/generator#86]
请将问题描述清楚,别耽误彼此打(xi)工(jiao)赚(nen)钱(mo)的时间.
如果能直接提供错误示例,请上传仓库或私发邮箱,对于私发邮箱的代码,承诺不泄露来源方信息(邮箱名,公司名等信息),阅后即焚.

#### 版本信息

​	生成器版本:
3.5.0

#### 问题详情
官方 templates 文件夹下的模板文件，只有 entity 是 LF 换行符，其他的都是  CRLF 换行符

#### 期望结果
统一修改为 LF

**Comment by qmdx** [comment]
https://github.com/baomidou/generator/commit/934f631a9f5b6ed6949f517ffba3a3d08c6d98ec
