### ISSUE TITLE
可运行demo

### ISSUE THREAD

**Issue by SkyLineCN** [baomidou/generator#89]
请将问题描述清楚,别耽误彼此打(xi)工(jiao)赚(nen)钱(mo)的时间.
如果能直接提供错误示例,请上传仓库或私发邮箱,对于私发邮箱的代码,承诺不泄露来源方信息(邮箱名,公司名等信息),阅后即焚.

#### 版本信息

​	生成器版本:3.5.0

​	数据库版本:mysql8.0

​	模板引擎版本:freemaker

#### 问题详情
readme.md有几个方法对不上，还有的方法被取消了，但是在readme里面还写的有。

#### 期望结果
尽快更新文档，谢谢。
请注意，附件代码有效日期为2021.7.24，后续更新可能失效。

附demo代码：
    //3.5.0版本使用新的类和方法
    public static void main(String[] args) {
        // 1、全局配置
        GlobalConfig globalConfig = GeneratorBuilder.globalConfigBuilder()
                .fileOverride()//覆盖已有文件，如果不需要覆盖的话可以把这句话注释
                .openDir(true)
                .enableKotlin()//开启 kotlin 模式
                .enableSwagger()//开启 swagger 模式
                // .outputDir("com")//地址为D盘下
                .author("skyLine")
                .dateType(DateType.TIME_PACK)
                .commentDate("yyyy-MM-dd")
                .build();
        // 2、数据源配置
        DataSourceConfig dataSourceConfig = new DataSourceConfig
                .Builder("jdbc:mysql://127.0.0.1:3306/cloud", "root", "root")
                .typeConvert(new MySqlTypeConvert())
                .keyWordsHandler(new MySqlKeyWordsHandler())
                .dbQuery(new MySqlQuery())
                .schema("mybatis-plus")
                .build();
        // 3、包配置
        PackageConfig packageConfig = new PackageConfig.Builder()
                .parent("com.skyline")
                .moduleName("mpgtest")
                .build();
        // 4、策略配置
        StrategyConfig strategyConfig = new StrategyConfig.Builder()
                .addInclude("student")//表名
                //.disableSqlFilter()// 启用sql过滤  默认过滤，这一段需要注释.解掉注释就屏蔽过滤
                .enableCapitalMode()// 开启大写命名
                .entityBuilder()// 实体配置构建者
                .enableLombok()// 开启lombok模型
                .versionColumnName("version") //乐观锁数据库表字段
                .naming(NamingStrategy.underline_to_camel)// 数据库表映射到实体的命名策略
                .controllerBuilder() //控制器属性配置构建
                .build();
        // 5、模板配置
        TemplateConfig templateConfig = new TemplateConfig.Builder()
                //.disable()//屏蔽某一个
                .build();//激活所有默认模板
        // 6、创建代码生成器
        AutoGenerator mpg = new AutoGenerator(dataSourceConfig)
                .strategy(strategyConfig)
                .global(globalConfig)
                .packageInfo(packageConfig)
                .template(templateConfig);
        //7 执行
        mpg.execute(new FreemarkerTemplateEngine());//我这里用的freemaker需要引入对应freemaker依赖
    }

POM：
        <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-generator</artifactId>
            <version>3.5.0</version>
        </dependency>

**Comment by jipeigong** [comment]
这是我的demo 供参考，希望作者可以将类似的完整demo放进来
```
public static void main(String[] args) {

        new SimpleAutoGenerator() {

            @Override
            public IConfigBuilder<DataSourceConfig> dataSourceConfigBuilder() {
                return new DataSourceConfig.Builder("jdbc:mysql://xxxx",
                        "root","xxxx");
            }

            @Override
            public IConfigBuilder<GlobalConfig> globalConfigBuilder() {
                String outputDir = new File(System.getProperty("user.dir")) +"/src/main/java";
                System.out.println("\n输出文件目录：" + outputDir);
                return new GlobalConfig.Builder().fileOverride().enableSwagger().outputDir(outputDir)
                        .author("JiPeigong").dateType(DateType.ONLY_DATE);
            }

            @Override
            public PackageConfig.Builder packageConfigBuilder() {
                return new PackageConfig.Builder().
                        parent("com.aienglish.news")
                        .moduleName("oauth");
            }

            @Override
            public IConfigBuilder<TemplateConfig> templateConfigBuilder() {
                return new TemplateConfig.Builder();
            }

            @Override
            public IConfigBuilder<StrategyConfig> strategyConfigBuilder() {
                return new StrategyConfig.Builder()
                        .addInclude("oauth_client_details")
                        .entityBuilder()// 实体配置构建者
                        .enableLombok()// 开启lombok模型
//                        .versionColumnName("version") //乐观锁数据库表字段
                        .naming(NamingStrategy.underline_to_camel)// 数据库表映射到实体的命名策略
                        .columnNaming(NamingStrategy.underline_to_camel)
                        .enableColumnConstant()
                        .controllerBuilder(); //控制器属性配置构建
            }

            @Override
            public AbstractTemplateEngine templateEngine() {
                return new FreemarkerTemplateEngine();
            }
        }.execute();
    }
```

**Comment by hibmm** [comment]
不能过滤表前缀了吗……好难受

**Comment by lanjerry** [comment]
@hibmm 使用策略配置的addTablePrefix，例如：
    /**
     * 策略配置
     */
    public static StrategyConfig strategyConfig() {
        return new StrategyConfig.Builder()
                .addInclude("t_simple")// 需要生成的表名
                .addTablePrefix("t_") //过滤表前缀
                .build();
    }

**Comment by hibmm** [comment]
@lanjerry 谢谢你，能贴个完整的demo吗，我用新的SimpleAutoGenerator()创建没问题，分开写配置就总是出问题

**Comment by lanjerry** [comment]
@hibmm 把你的贴出来并说下哪里有问题

**Comment by hibmm** [comment]
@lanjerry 我搞定了，感谢大佬帮助
贴出代码大家参考一下


 ```
   /**
     * 全局
     * @return
     */
    public static GlobalConfig globalConfig(){
        String outputDir = new File(System.getProperty("user.dir")) +"/src/main/java";
        return new GlobalConfig.Builder()
                .author("baimm")
                .fileOverride()
                .enableSwagger()
                .openDir(true)
                .outputDir(outputDir)
                .build();
    }

    /**
     * 数据库连接
     * @return
     */
    public static DataSourceConfig dataSourceConfig(){
        return new DataSourceConfig.Builder("jdbc:mysql://localhost:3306/blog?serverTimezone=GMT%2B8&allowMultiQueries=true", "root", "123456")
                .build();
    }

    /**
     * 包名配置
     * @return
     */
    public static PackageConfig packageConfig(){
        return new PackageConfig.Builder()
                .parent("com.hibmm")
                .moduleName("bmmblog")
                .service("Service")
                .serviceImpl("Service.Impl")
                .build();
    }

    /**
     * 策略配置
     * @return
     */
    public static StrategyConfig strategyConfig() {
        return new StrategyConfig.Builder()
                .addInclude("tb_article")// 需要生成的表名
                .addTablePrefix("tb_") //过滤表前缀
                .entityBuilder()
                .enableLombok()
                .build();
    }


    public static void main(String[] args) {


        AutoGenerator mpg = new AutoGenerator(dataSourceConfig())
                .strategy(strategyConfig())
                .global(globalConfig())
                .packageInfo(packageConfig());
//                .template()
        mpg.execute();
    }
```
