### ISSUE TITLE
TableField类，是否能加入一些约束信息？

### ISSUE THREAD

**Issue by coder-chenhao** [baomidou/generator#9]
### 当前使用版本(必填,否则不予处理)

3.3.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

就比如我在数据库建模的时候，给这个字段加了非空限制，TableField类能否加入这种约束信息，以便于代码生成器生成一些模型验证的注解，如@NotBank，@Size等。

**Comment by nieqiurong** [comment]
默认的都没处理那块,只能通过customMap去处理,精力有限,看有没有人弄了

**Comment by coder-chenhao** [comment]
> 默认的都没处理那块,只能通过customMap去处理,精力有限,看有没有人弄了

嗯嗯，我通过调式源码发现，可以通过继承对应的SqlQuery类，然后在DataSourceConfig中配。最后从自定义模板中通过customMap获取自己想要查询的列。
