### ISSUE TITLE
去除数据库is字段前缀不生效，且tinyint(1)无法自动映射为Boolean

### ISSUE THREAD

**Issue by DamonEvil** [baomidou/generator#90]
请将问题描述清楚,别耽误彼此打(xi)工(jiao)赚(nen)钱(mo)的时间.
如果能直接提供错误示例,请上传仓库或私发邮箱,对于私发邮箱的代码,承诺不泄露来源方信息(邮箱名,公司名等信息),阅后即焚.

#### 版本信息

​	生成器版本: mybatis-plus-generator 3.4.1

​	数据库版本: mysql 8.0.23

​	模板引擎版本: freemarker 2.3.31

#### 问题详情
setEntityBooleanColumnRemoveIsPrefix(true)配置为true之后不生效，数据库中的is_deleted字段还是会映射为实体类的isDeleted字段
#### 复现步骤
setEntityBooleanColumnRemoveIsPrefix(true)后生成代码，查看实体类
#### 错误结果
实体类字段
  @ApiModelProperty(value = "逻辑删除（1表示已删除，2表示未删除）")
  @TableField("is_deleted")
  @TableLogic
  private Integer idDeleted;
#### 期望结果
    @ApiModelProperty(value = "逻辑删除（1表示已删除，2表示未删除）")
    @TableField("is_deleted")
    @TableLogic
    private Boolean deleted;

**Comment by lanjerry** [comment]
麻烦升级至3.5.0版本，该需求已实现，使用的策略配置可参考如下

<dependency>
    <groupId>com.baomidou</groupId>
    <artifactId>mybatis-plus-generator</artifactId>
    <version>3.5.0</version>
</dependency>

    /**
     * 策略配置
     */
    public StrategyConfig strategyConfig() {
        return new StrategyConfig.Builder()
                .addInclude("t_simple")// 需要生成的表名
                .entityBuilder()// 实体配置构建者
                .naming(NamingStrategy.underline_to_camel)// 数据库表映射到实体的命名策略
                .logicDeleteColumnName("is_deleted")// 设置逻辑删除对应的字段名称，也能设置实体属性名称logicDeletePropertyName
                .enableRemoveIsPrefix()// 开启Boolean类型字段移除is前缀
                .build();
    }

**Comment by lanjerry** [comment]
@DamonEvil

**Comment by simon-mao** [comment]
在 3.5.2 上复现。

**sql**
```
is_deleted  tinyint unsigned default '0' not null comment '是否删除：0=否；1=是'
```

**pom.xml**
```
        <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-generator</artifactId>
            <version>3.5.2</version>
        </dependency>
```

```
                        builder.entityBuilder()
                                .naming(NamingStrategy.underline_to_camel) // 下划线转驼峰命名
                                .enableTableFieldAnnotation() // 字段注解
                                .enableColumnConstant() // 生成字段常量
                                .enableActiveRecord() // 生成 pkVal() 方法
                                .enableChainModel() // 链式
                                // .logicDeletePropertyName("isDeleted")
                                .logicDeleteColumnName("is_deleted") // 逻辑删除字段
                                .enableRemoveIsPrefix() // 移除 is 前缀
                                // .fileOverride()
                                .enableLombok(); // Lombok
```

**生成结果**
```
    /**
     * 是否删除：0=否；1=是
     */
    @TableField("is_deleted")
    @TableLogic
    private Integer isDeleted;
```

**Comment by simon-mao** [comment]
经过阅读源码已找出问题，因我在 sql 字段上加入了 unsined ，所以生成器在比较的时候不成功，导致无法转换为 `Boolean` 字段和去除 `is_` 前缀。

```
    @Override
    public IColumnType processTypeConvert(GlobalConfig config, String fieldType) {
        return TypeConverts.use(fieldType)
            .test(containsAny("char", "text", "json", "enum").then(STRING))
            .test(contains("bigint").then(LONG))
            .test(containsAny("tinyint(1)", "bit(1)").then(BOOLEAN))
            .test(contains("bit").then(BYTE))
            .test(contains("int").then(INTEGER))
            .test(contains("decimal").then(BIG_DECIMAL))
            .test(contains("clob").then(CLOB))
            .test(contains("blob").then(BLOB))
            .test(contains("binary").then(BYTE_ARRAY))
            .test(contains("float").then(FLOAT))
            .test(contains("double").then(DOUBLE))
            .test(containsAny("date", "time", "year").then(t -> toDateType(config, t)))
            .or(STRING);
    }
```
