### ISSUE TITLE
3.5.0 Controller的hyphenStyle无效

### ISSUE THREAD

**Issue by YellowDoing** [baomidou/generator#93]
请将问题描述清楚,别耽误彼此打(xi)工(jiao)赚(nen)钱(mo)的时间.
如果能直接提供错误示例,请上传仓库或私发邮箱,对于私发邮箱的代码,承诺不泄露来源方信息(邮箱名,公司名等信息),阅后即焚.

#### 版本信息

​	生成器版本:

​	数据库版本:

​	模板引擎版本:

#### 问题详情

Controller的hyphenStyle无论用默认还是true，生成的Mapping都是中划线连起来的

**Comment by lanjerry** [comment]
@YellowDoing 说仔细点啊大哥，把错误结果和期望结果说下啊
